test_textbox:	
	g++ src/fifechanfpsdemo.cpp src/fpsbutton.cpp src/fpscheckbox.cpp src/fpsdemo.cpp -I./include -I/usr/include/SDL2 -I/usr/local/include/fifechan -lSDL2 -lSDL2_image -lSDL2_mixer -lfifechan -lfifechan_sdl -lfifechan_opengl -lGL -lGLU -o fifechanfpsdemo.out

clean:
	rm -rf *.out
