#!/usr/bin/env python3
"""generate_enum.py Generate a C++ header mirroring SDL3 keycodes.

Reads JSON from stdin (produced by parse_sdl3.py) and writes a C++ header
to stdout. The generated file contains:

- A `FIFECHAN_SDL_KEYMAP_VERSION` macro (the SDL3 version it was built from).
- An anonymous `fcn::KeyType` enum matching all `SDLK_*` constants as uint32_t.
- A static_assert on the enum size.

Usage:
    parse_sdl3.py /path/to/SDL_keycode.h | python3 generate_enum.py > key_gen.h
"""

import json
import sys

HEADER = """\
// SPDX-License-Identifier: LGPL-2.1-or-later OR BSD-3-Clause
// SPDX-FileCopyrightText: 2005 - 2026 Fifengine contributors
//
// ---------------------------------------------------------------------------
// Warning, this file is autogenerated. Do not edit directly.
// ---------------------------------------------------------------------------
// Generated from SDL_keycode.h of SDL3 v{version}
// ---------------------------------------------------------------------------
// To re-generate:
// 1. cmake --build . --target sync_keys_with_SDL3
// or delete this file and rebuild.
// ---------------------------------------------------------------------------

#ifndef FIFECHAN_KEY_GEN_H
#define FIFECHAN_KEY_GEN_H

#include <cstdint>

/** SDL3 version used to generate this key map. */
#define FIFECHAN_SDL_KEYMAP_VERSION {version_num}u

namespace fcn
{{

/** Mirrors SDL3's SDLK_* constants as uint32_t.
 *
 * Keycodes are SEMANTIC they identify the intended character/symbol,
 * not the physical key position. SDLK_a is the "a" key on any keyboard
 * layout (QWERTY, AZERTY, Dvorak).
 *
 * Scancodes are PHYSICAL SDL_SCANCODE_A is always the same physical
 * key position regardless of what character it produces. The OS maps
 * scancodes to keycodes based on the active keyboard layout.
 */
enum KeyType : uint32_t
{{
{body}
}};

}} // namespace fcn

static_assert(sizeof(fcn::KeyType) == sizeof(uint32_t),
              "KeyType must be 32-bit to match SDL_Keycode");

#endif // FIFECHAN_KEY_GEN_H
"""

NAMES_TO_UPPER = {
    'RETURN', 'ESCAPE', 'BACKSPACE', 'TAB', 'SPACE',
    'DELETE', 'CAPSLOCK', 'INSERT', 'HOME', 'PAGEUP',
    'END', 'PAGEDOWN', 'PRINTSCREEN', 'SCROLLLOCK', 'PAUSE',
    'NUMLOCKCLEAR', 'APPLICATION', 'POWER', 'EXECUTE', 'HELP',
    'MENU', 'SELECT', 'STOP', 'AGAIN', 'UNDO', 'CUT', 'COPY',
    'PASTE', 'FIND', 'MUTE', 'VOLUMEUP', 'VOLUMEDOWN',
    'ALTERASE', 'SYSREQ', 'CANCEL', 'CLEAR', 'PRIOR', 'RETURN2',
    'SEPARATOR', 'OUT', 'OPER', 'CLEARAGAIN', 'CRSEL', 'EXSEL',
    'MODE', 'SLEEP', 'WAKE',
}

CONFLICT_RENAME = {
    'LESS': 'KEY_LESS',
    'GREATER': 'KEY_GREATER',
    'UNKNOWN': 'KEY_UNKNOWN',
    'DELETE': 'KEY_DELETE',   # <winnt.h> #define DELETE
    'OUT': 'KEY_OUT',         # <windef.h> #define OUT
    'IN': 'KEY_IN',           # <windef.h> #define IN
    'NEAR': 'KEY_NEAR',       # <windef.h> #define NEAR
    'FAR': 'KEY_FAR',         # <windef.h> #define FAR
}

def to_enum_name(name: str) -> str:
    """Convert SDLK_FOO to FOO, prefix numeric-leading names with _."""
    s = name.removeprefix('SDLK_')
    if s and s[0].isdigit():
        s = '_' + s
    if s in CONFLICT_RENAME:
        return CONFLICT_RENAME[s]
    return s

def generate(data: dict) -> str:
    v = data['version']
    maj, min_, mic = v
    version_num = maj * 1_000_000 + min_ * 1_000 + mic

    lines = []
    for k in data['keys']:
        name = k['name']
        value = k['value']
        comment = k['comment']
        enum_entry = to_enum_name(name)
        if comment:
            lines.append(f'    {enum_entry:45s} = {value}u, // {comment}')
        else:
            lines.append(f'    {enum_entry:45s} = {value}u,')

    body = '\n'.join(lines)
    return HEADER.format(
        version=f'{maj}.{min_}.{mic}',
        version_num=version_num,
        body=body,
    )


if __name__ == '__main__':
    data = json.load(sys.stdin)
    print(generate(data), end='')
