#!/usr/bin/env python3
"""Generate a C++ header mirroring SDL3 keycodes.

Reads JSON from stdin, produced by `parse_sdl3.py`, and writes a C++ header
to stdout. The generated file contains:

- `FIFECHAN_SDL_KEYMAP_VERSION` with the SDL3 version used.
- An anonymous `fcn::KeyType` enum matching all `SDLK_*` constants.
- A `static_assert` verifying the enum size.

Usage:
    parse_sdl3.py /path/to/SDL_keycode.h | python3 generate_enum.py > key_gen.h
"""

import json
import sys

HEADER = """\
// SPDX-License-Identifier: LGPL-2.1-or-later OR BSD-3-Clause
// SPDX-FileCopyrightText: 2005 - 2026 Fifengine contributors

// ---------------------------------------------------------------------------
// This file is autogenerated from SDL_keycode.h of SDL3 v{version}.
// Do not edit.
// ---------------------------------------------------------------------------

#ifndef FIFECHAN_KEY_GEN_H
#define FIFECHAN_KEY_GEN_H

#include <cstdint>

// Platform config include
#include "fifechan/platform.hpp"

// SDL3 version used to generate this key map.
#define FIFECHAN_SDL_KEYMAP_VERSION {version_num}u

namespace fcn
{{

    class FIFEGUI_API Key
    {{
        public:
            explicit Key(int value = 0);

            bool isCharacter() const;
            bool isNumber() const;
            bool isLetter() const;
            int getValue() const;

            bool operator==(Key const & other) const;
            bool operator!=(Key const & other) const;

            enum KeyType : uint32_t
            {{
{body}
            }};

            static_assert(sizeof(Keys::KeyType) == sizeof(uint32_t), "KeyType must be 32-bit to match SDL_Keycode");

        protected:
            int mValue;
    }};

}} // namespace fcn

#endif // FIFECHAN_KEY_GEN_H
"""

NAMES_TO_UPPER = {
    'RETURN', 'ESCAPE', 'BACKSPACE', 'TAB', 'SPACE',
    'DELETE', 'CAPSLOCK', 'INSERT', 'HOME', 'PAGEUP',
    'END', 'PAGEDOWN', 'PRINTSCREEN', 'SCROLLLOCK', 'PAUSE',
    'NUMLOCKCLEAR', 'APPLICATION', 'POWER', 'EXECUTE', 'HELP',
    'MENU', 'SELECT', 'STOP', 'AGAIN', 'UNDO', 'CUT', 'COPY',
    'PASTE', 'FIND', 'MUTE', 'VOLUMEUP', 'VOLUMEDOWN',
    'ALTERASE', 'SYSREQ', 'CANCEL', 'CLEAR', 'PRIOR', 'RETURN2',
    'SEPARATOR', 'OUT', 'OPER', 'CLEARAGAIN', 'CRSEL', 'EXSEL',
    'MODE', 'SLEEP', 'WAKE',
}

CONFLICT_RENAME = {
    'LESS': 'KEY_LESS',
    'GREATER': 'KEY_GREATER',
    'UNKNOWN': 'KEY_UNKNOWN',
    'DELETE': 'KEY_DELETE',   # <winnt.h>
    'RETURN': 'KEY_RETURN',   # `return` is a C++ keyword
    'OUT': 'KEY_OUT',         # <windef.h>
    'IN': 'KEY_IN',           # <windef.h>
    'NEAR': 'KEY_NEAR',       # <windef.h>
    'FAR': 'KEY_FAR',         # <windef.h>
    'CANCEL': 'KEY_CANCEL',   # <winuser.h>
    'CLEAR': 'KEY_CLEAR',     # <winuser.h>
    'COPY': 'KEY_COPY',       # <winuser.h>
    'SELECT': 'KEY_SELECT',   # <winuser.h>
}

def to_enum_name(name: str) -> str:
    """Convert SDLK_FOO to FOO, prefix numeric-leading names with _."""
    s = name.removeprefix('SDLK_')
    if s and s[0].isdigit():
        s = '_' + s
    if s in CONFLICT_RENAME:
        return CONFLICT_RENAME[s]
    return s

def generate(data: dict) -> str:
    v = data['version']
    maj, min_, mic = v
    version_num = maj * 1_000_000 + min_ * 1_000 + mic

    lines = []
    for k in data['keys']:
        name = k['name']
        value = k['value']
        comment = k['comment']
        enum_entry = to_enum_name(name)
        if comment:
            lines.append(f'            {enum_entry:20s} = {value}u, // {comment}')
        else:
            lines.append(f'            {enum_entry:20s} = {value}u,')

    body = '\n'.join(lines)

    return HEADER.format(
        version=f'{maj}.{min_}.{mic}',
        version_num=version_num,
        body=body,
    )


if __name__ == '__main__':
    data = json.load(sys.stdin)
    print(generate(data), end='')
