FifeGUI: fcn::Math< T > Class Template Reference
fcn::Math< T > Class Template Reference
Utilities & Math
#include <math.hpp>
Public Types
using num_type = T
using traits_type = float_traits<num_type>
Static Public Member Functions
static T ACos (T _val)
static T ASin (T _val)
static T ATan (T _val)
static T ATan2 (T _x, T _y)
static T Ceil (T _val)
static T Cos (T _val)
static num_type degToRad ()
static num_type epsilon ()
static bool Equal (T _val1, T _val2)
static T Exp (T _val)
static T FAbs (T _val)
static T Floor (T _val)
static T FMod (T _x, T _y)
static num_type halfPi ()
static num_type inversePi ()
static num_type inverseTwoPi ()
static num_type invLog10 ()
static num_type invLog2 ()
static T InvSqrt (T _val)
static T Log (T _val)
static T Log10 (T _val)
static num_type log10 ()
static T Log2 (T _val)
static num_type log2 ()
static num_type max ()
static num_type pi ()
static T Pow (T _base, T _exponent)
static num_type radToDeg ()
static T Sin (T _val)
static T Sqr (T _val)
static T Sqrt (T _val)
static T Tan (T _val)
static num_type twoPi ()
static num_type zeroTolerance ()
Detailed Description
template<typename T>
class fcn::Math< T >
Template utility providing math functions and constants for numeric type T.
Utility math functions and constants templated on numeric type T. Use Mathf and Mathd for float and double respectively.
Definition at line 233 of file math.hpp.
Member Typedef Documentation
num_type
template<typename T> using fcn::Math< T >::num_type = T
Type definitions.
Definition at line 239 of file math.hpp.
traits_type
template<typename T> using fcn::Math< T >::traits_type = float_traits<num_type>
Trait alias providing numeric constants and helpers for num_type.
Definition at line 242 of file math.hpp.
Member Function Documentation
ACos()
template<typename T> T fcn::Math< T >::ACos (T _val) inline static
Arc cosine (clamped).
Definition at line 393 of file math.hpp.
References pi().
ASin()
template<class T> T fcn::Math< T >::ASin (T _val) inline static
Arc sine (clamped).
Definition at line 407 of file math.hpp.
References halfPi().
ATan()
template<class T> T fcn::Math< T >::ATan (T _val) inline static
Arc tangent.
Definition at line 421 of file math.hpp.
ATan2()
template<class T> T fcn::Math< T >::ATan2 (T _x, T _y) inline static
Two-argument arc tangent.
Definition at line 427 of file math.hpp.
Ceil()
template<class T> T fcn::Math< T >::Ceil (T _val) inline static
Ceiling of value.
Definition at line 433 of file math.hpp.
Cos()
template<class T> T fcn::Math< T >::Cos (T _val) inline static
Cosine of value.
Definition at line 439 of file math.hpp.
degToRad()
template<typename T> num_type fcn::Math< T >::degToRad () inline static
Degrees-to-radians factor.
Definition at line 293 of file math.hpp.
epsilon()
template<typename T> num_type fcn::Math< T >::epsilon () inline static
Returns machine epsilon for the numeric type.
Definition at line 245 of file math.hpp.
Referenced by Equal().
Equal()
template<class T> bool fcn::Math< T >::Equal (T _val1, T _val2) inline static
Approximate equality check using epsilon.
Definition at line 523 of file math.hpp.
References epsilon().
Exp()
template<class T> T fcn::Math< T >::Exp (T _val) inline static
Exponential e^x.
Definition at line 445 of file math.hpp.
FAbs()
template<class T> T fcn::Math< T >::FAbs (T _val) inline static
Absolute value (floating).
Definition at line 451 of file math.hpp.
Floor()
template<class T> T fcn::Math< T >::Floor (T _val) inline static
Floor of value.
Definition at line 457 of file math.hpp.
FMod()
template<class T> T fcn::Math< T >::FMod (T _x, T _y) inline static
Floating-point modulus.
Definition at line 463 of file math.hpp.
halfPi()
template<typename T> num_type fcn::Math< T >::halfPi () inline static
Half of pi.
Definition at line 275 of file math.hpp.
Referenced by ASin().
inversePi()
template<typename T> num_type fcn::Math< T >::inversePi () inline static
1/pi constant.
Definition at line 281 of file math.hpp.
inverseTwoPi()
template<typename T> num_type fcn::Math< T >::inverseTwoPi () inline static
1/(2*pi) constant.
Definition at line 287 of file math.hpp.
invLog10()
template<typename T> num_type fcn::Math< T >::invLog10 () inline static
1/ln(10) helper.
Definition at line 323 of file math.hpp.
Referenced by Log10().
invLog2()
template<typename T> num_type fcn::Math< T >::invLog2 () inline static
1/ln(2) helper.
Definition at line 317 of file math.hpp.
Referenced by Log2().
InvSqrt()
template<class T> T fcn::Math< T >::InvSqrt (T _val) inline static
Inverse square root (1/sqrt(x)).
Definition at line 469 of file math.hpp.
Log()
template<class T> T fcn::Math< T >::Log (T _val) inline static
Natural logarithm.
Definition at line 475 of file math.hpp.
Log10()
template<class T> T fcn::Math< T >::Log10 (T _val) inline static
Log base 10.
Definition at line 486 of file math.hpp.
References invLog10().
log10()
template<typename T> num_type fcn::Math< T >::log10 () inline static
Natural log base 10.
Definition at line 311 of file math.hpp.
Log2()
template<class T> T fcn::Math< T >::Log2 (T _val) inline static
Log base 2.
Definition at line 481 of file math.hpp.
References invLog2().
log2()
template<typename T> num_type fcn::Math< T >::log2 () inline static
Natural log base 2.
Definition at line 305 of file math.hpp.
max()
template<typename T> num_type fcn::Math< T >::max () inline static
Maximum finite value for the numeric type.
Definition at line 257 of file math.hpp.
pi()
template<typename T> num_type fcn::Math< T >::pi () inline static
Pi constant.
Definition at line 263 of file math.hpp.
Referenced by ACos().
Pow()
template<class T> T fcn::Math< T >::Pow (T _base, T _exponent) inline static
Power function.
Definition at line 493 of file math.hpp.
radToDeg()
template<typename T> num_type fcn::Math< T >::radToDeg () inline static
Radians-to-degrees factor.
Definition at line 299 of file math.hpp.
Sin()
template<class T> T fcn::Math< T >::Sin (T _val) inline static
Sine of value.
Definition at line 499 of file math.hpp.
Sqr()
template<class T> T fcn::Math< T >::Sqr (T _val) inline static
Square of value.
Definition at line 505 of file math.hpp.
Sqrt()
template<class T> T fcn::Math< T >::Sqrt (T _val) inline static
Square root.
Definition at line 511 of file math.hpp.
Tan()
template<class T> T fcn::Math< T >::Tan (T _val) inline static
Tangent of value.
Definition at line 517 of file math.hpp.
twoPi()
template<typename T> num_type fcn::Math< T >::twoPi () inline static
Two times pi.
Definition at line 269 of file math.hpp.
zeroTolerance()
template<typename T> num_type fcn::Math< T >::zeroTolerance () inline static
Recommended zero tolerance for comparisons.
Definition at line 251 of file math.hpp.
The documentation for this class was generated from the following file:
math.hpp