FifeGUI: fcn::VisibilityEventHandler Class Reference
fcn::VisibilityEventHandler Class Reference
Listeners
#include <visibilityeventhandler.hpp>
Public Member Functions
VisibilityEventHandler & operator= (VisibilityEventHandler &&)=delete
VisibilityEventHandler & operator= (VisibilityEventHandler const &)=delete
VisibilityEventHandler (Gui *gui)
VisibilityEventHandler (VisibilityEventHandler &&)=delete
VisibilityEventHandler (VisibilityEventHandler const &)=delete
void widgetHidden (Event const &e) override
void widgetShown (Event const &e) override
Public Member Functions inherited from fcn::WidgetListener
virtual void ancestorHidden (Event const &event)
virtual void ancestorMoved (Event const &event)
virtual void ancestorShown (Event const &event)
WidgetListener & operator= (WidgetListener &&)=default
WidgetListener & operator= (WidgetListener const &)=default
WidgetListener (WidgetListener &&)=default
WidgetListener (WidgetListener const &)=default
virtual void widgetMoved (Event const &event)
virtual void widgetResized (Event const &event)
Protected Attributes
Gui * mGui
Additional Inherited Members
Protected Member Functions inherited from fcn::WidgetListener
WidgetListener ()=default
Detailed Description
Handles changes in widget visibility states.
The VisibilityEventHandler class handles widget visibility changes. It addresses input issues that arise when widgets are shown or hidden.
Definition at line 24 of file visibilityeventhandler.hpp.
Constructor & Destructor Documentation
VisibilityEventHandler()
fcn::VisibilityEventHandler::VisibilityEventHandler (Gui * gui) explicit
Construct a VisibilityEventHandler bound to a Gui instance.
Parameters
gui The Gui instance to inform about visibility changes.
Definition at line 12 of file visibilityeventhandler.cpp.
References mGui.
Member Function Documentation
widgetHidden()
void fcn::VisibilityEventHandler::widgetHidden (Event const & e) override virtual
Informs gui that a widget was hidden.
Reimplemented from fcn::WidgetListener.
Definition at line 14 of file visibilityeventhandler.cpp.
References fcn::Event::getSource(), and mGui.
Referenced by fcn::Widget::distributeAncestorHiddenEvent(), fcn::Widget::remove(), fcn::Widget::removeAllChildren(), and fcn::Widget::setVisible().
widgetShown()
void fcn::VisibilityEventHandler::widgetShown (Event const & e) override virtual
Informs gui that a widget was shown.
Reimplemented from fcn::WidgetListener.
Definition at line 19 of file visibilityeventhandler.cpp.
References fcn::Event::getSource(), and mGui.
Referenced by fcn::Widget::add(), fcn::Widget::distributeAncestorShownEvent(), and fcn::Widget::setVisible().
Member Data Documentation
mGui
Gui* fcn::VisibilityEventHandler::mGui protected
Pointer to the Gui used to handle visibility-related updates.
Definition at line 53 of file visibilityeventhandler.hpp.
Referenced by VisibilityEventHandler(), widgetHidden(), and widgetShown().
The documentation for this class was generated from the following files:
visibilityeventhandler.hpp
visibilityeventhandler.cpp