FifeGUI: fcn::ScrollArea Class Reference
fcn::ScrollArea Class Reference
Widgets
#include <scrollarea.hpp>
Public Types
enum class ScrollPolicy : uint8_t { ShowAlways = 0 , ShowNever , ShowAuto }
Public Types inherited from fcn::Widget
enum class SelectionMode : uint8_t { None = 0 , Border = 1 , Background = 2 }
Public Member Functions
void adjustSize () override
void draw (Graphics *graphics) override
void expandContent ()
void expandContent (bool recursion) override
Rectangle getChildrenArea () override
Widget * getContent () const
int getDownButtonScrollAmount () const
int getHorizontalMaxScroll ()
int getHorizontalScrollAmount () const
ScrollPolicy getHorizontalScrollPolicy () const
int getLeftButtonScrollAmount () const
int getRightButtonScrollAmount () const
int getScrollbarWidth () const
int getUpButtonScrollAmount () const
int getVerticalMaxScroll ()
int getVerticalScrollAmount () const
ScrollPolicy getVerticalScrollPolicy () const
virtual Widget * getWidgetAt (int x, int y)
bool isOpaque () const
void logic () override
void mouseDragged (MouseEvent &mouseEvent) override
void mousePressed (MouseEvent &mouseEvent) override
void mouseReleased (MouseEvent &mouseEvent) override
void mouseWheelMovedDown (MouseEvent &mouseEvent) override
void mouseWheelMovedLeft (MouseEvent &mouseEvent) override
void mouseWheelMovedRight (MouseEvent &mouseEvent) override
void mouseWheelMovedUp (MouseEvent &mouseEvent) override
ScrollArea & operator= (ScrollArea &&)=delete
ScrollArea & operator= (ScrollArea const &)=delete
void resizeToContent ()
void resizeToContent (bool recursion) override
ScrollArea (ScrollArea &&)=delete
ScrollArea (ScrollArea const &)=delete
ScrollArea (Widget *content)
ScrollArea (Widget *content, ScrollPolicy hPolicy, ScrollPolicy vPolicy)
void setContent (Widget *widget)
void setDimension (Rectangle const &dimension)
void setDownButtonScrollAmount (int amount)
void setHeight (int height)
void setHorizontalScrollAmount (int hScroll)
void setHorizontalScrollPolicy (ScrollPolicy hPolicy)
void setLeftButtonScrollAmount (int amount)
void setOpaque (bool opaque)
void setRightButtonScrollAmount (int amount)
void setScrollAmount (int hScroll, int vScroll)
void setScrollbarWidth (int width)
void setScrollPolicy (ScrollPolicy hPolicy, ScrollPolicy vPolicy)
void setUpButtonScrollAmount (int amount)
void setVerticalScrollAmount (int vScroll)
void setVerticalScrollPolicy (ScrollPolicy vPolicy)
void setWidth (int width)
void showWidgetPart (Widget *widget, Rectangle area) override
Public Member Functions inherited from fcn::MouseListener
virtual void mouseClicked (MouseEvent &mouseEvent)
virtual void mouseEntered (MouseEvent &mouseEvent)
virtual void mouseExited (MouseEvent &mouseEvent)
MouseListener (MouseListener &&)=default
MouseListener (MouseListener const &)=default
virtual void mouseMoved (MouseEvent &mouseEvent)
MouseListener & operator= (MouseListener &&)=default
MouseListener & operator= (MouseListener const &)=default
Public Member Functions inherited from fcn::Widget
virtual void _draw (Graphics *graphics)
virtual FocusHandler * _getFocusHandler ()
virtual std::list< FocusListener * > const & _getFocusListeners ()
virtual FocusHandler * _getInternalFocusHandler ()
virtual std::list< KeyListener * > const & _getKeyListeners ()
virtual std::list< MouseListener * > const & _getMouseListeners ()
virtual void _logic ()
virtual void _setFocusHandler (FocusHandler *focusHandler)
virtual void _setParent (Widget *parent)
void adaptLayout ()
virtual void adaptLayout (bool top)
void addActionListener (ActionListener *actionListener)
void addDeathListener (DeathListener *deathListener)
void addFocusListener (FocusListener *focusListener)
void addKeyListener (KeyListener *keyListener)
void addMouseListener (MouseListener *mouseListener)
void addWidgetListener (WidgetListener *widgetListener)
virtual void drawBorder (Graphics *graphics)
virtual void drawOutline (Graphics *graphics)
virtual void drawSelectionFrame (Graphics *graphics)
void expandContent ()
virtual void focusNext ()
virtual void focusPrevious ()
virtual void fontChanged ()
virtual void getAbsolutePosition (int &x, int &y) const
std::string const & getActionEventId () const
Color const & getBackgroundColor () const
Color const & getBaseColor () const
Color const & getBorderColor () const
unsigned int getBorderSize () const
unsigned int getChildrenCount () const
Rectangle const & getDimension () const
Size const & getFixedSize () const
Font * getFont () const
Color const & getForegroundColor () const
int getHeight () const
std::string const & getId () const
void getLastPosition (int &x, int &y) const
int getMarginBottom () const
int getMarginLeft () const
int getMarginRight () const
int getMarginTop () const
Size const & getMaxSize () const
Size const & getMinSize () const
Color const & getOutlineColor () const
unsigned int getOutlineSize () const
unsigned int getPaddingBottom () const
unsigned int getPaddingLeft () const
unsigned int getPaddingRight () const
unsigned int getPaddingTop () const
virtual Widget * getParent () const
Color const & getSelectionColor () const
SelectionMode getSelectionMode () const
virtual Widget * getTop () const
unsigned int getVisibleChildrenCount () const
Widget * getWidgetAt (int x, int y)
virtual Widget * getWidgetAt (int x, int y, Widget *exclude)
std::list< Widget * > getWidgetsIn (Rectangle const &area)
virtual std::list< Widget * > getWidgetsIn (Rectangle const &area, Widget *ignore)
int getWidth () const
int getX () const
int getY () const
bool isEnabled () const
bool isFixedSize () const
bool isFocusable () const
virtual bool isFocused () const
bool isHorizontalExpand () const
bool isLastPositionSet () const
virtual bool isLayouted ()
virtual bool isModalFocusable () const
virtual bool isModalFocused () const
virtual bool isModalMouseInputFocusable () const
virtual bool isModalMouseInputFocused () const
bool isSetVisible () const
bool isTabInEnabled () const
bool isTabOutEnabled () const
bool isVerticalExpand () const
bool isVisible () const
virtual void moveToBottom (Widget *widget)
virtual void moveToTop (Widget *widget)
Widget & operator= (Widget &&)=delete
Widget & operator= (Widget const &)=delete
virtual void releaseModalFocus ()
virtual void releaseModalMouseInputFocus ()
void removeActionListener (ActionListener *actionListener)
void removeDeathListener (DeathListener *deathListener)
void removeFocusListener (FocusListener *focusListener)
void removeKeyListener (KeyListener *keyListener)
void removeMouseListener (MouseListener *mouseListener)
void removeWidgetListener (WidgetListener *widgetListener)
virtual void requestFocus ()
virtual void requestModalFocus ()
virtual void requestModalMouseInputFocus ()
virtual void requestMoveToBottom ()
virtual void requestMoveToTop ()
void resizeToContent ()
void setActionEventId (std::string const &actionEventId)
virtual void setBackgroundColor (Color const &color)
virtual void setBaseColor (Color const &color)
virtual void setBorderColor (Color const &color)
void setBorderSize (unsigned int size)
void setDimension (Rectangle const &dimension)
void setEnabled (bool enabled)
void setFixedSize (Size const &size)
void setFocusable (bool focusable)
virtual void setFont (Font *font)
virtual void setForegroundColor (Color const &color)
void setHeight (int height)
void setHorizontalExpand (bool expand)
void setId (std::string const &id)
void setInternalFocusHandler (FocusHandler *internalFocusHandler)
void setLastPosition (int x, int y)
void setMargin (int margin)
void setMarginBottom (int margin)
void setMarginLeft (int margin)
void setMarginRight (int margin)
void setMarginTop (int margin)
void setMaxSize (Size const &size)
void setMinSize (Size const &size)
virtual void setOutlineColor (Color const &color)
void setOutlineSize (unsigned int size)
void setPadding (unsigned int padding)
void setPaddingBottom (unsigned int padding)
void setPaddingLeft (unsigned int padding)
void setPaddingRight (unsigned int padding)
void setPaddingTop (unsigned int padding)
void setPosition (int x, int y)
virtual void setSelectionColor (Color const &color)
virtual void setSelectionMode (SelectionMode mode)
void setSize (int width, int height)
void setTabInEnabled (bool enabled)
void setTabOutEnabled (bool enabled)
void setVerticalExpand (bool expand)
void setVisible (bool visible)
void setWidth (int width)
void setX (int x)
void setY (int y)
virtual void showPart (Rectangle rectangle)
Widget ()
Widget (Widget &&)=delete
Widget (Widget const &)=delete
Protected Member Functions
virtual void checkPolicies ()
virtual void drawBackground (Graphics *graphics)
virtual void drawDownButton (Graphics *graphics)
virtual void drawHBar (Graphics *graphics)
virtual void drawHMarker (Graphics *graphics)
virtual void drawLeftButton (Graphics *graphics)
virtual void drawRightButton (Graphics *graphics)
virtual void drawUpButton (Graphics *graphics)
virtual void drawVBar (Graphics *graphics)
virtual void drawVMarker (Graphics *graphics)
Rectangle getDownButtonDimension ()
Rectangle getHorizontalBarDimension ()
Rectangle getHorizontalMarkerDimension ()
Rectangle getLeftButtonDimension ()
Rectangle getRightButtonDimension ()
Rectangle getUpButtonDimension ()
Rectangle getVerticalBarDimension ()
Rectangle getVerticalMarkerDimension ()
Protected Member Functions inherited from fcn::MouseListener
MouseListener ()=default
Protected Member Functions inherited from fcn::Widget
void add (Widget *widget)
void calculateSize ()
void distributeActionEvent ()
void distributeAncestorHiddenEvent (Widget *ancestor)
void distributeAncestorMovedEvent (Widget *ancestor)
void distributeAncestorShownEvent (Widget *ancestor)
void distributeHiddenEvent ()
void distributeMovedEvent ()
void distributeResizedEvent ()
void distributeShownEvent ()
virtual Widget * findWidgetById (std::string const &id)
std::list< Widget * > const & getChildren () const
virtual void remove (Widget *widget)
virtual void removeAllChildren ()
void resizeToChildren ()
Protected Attributes
bool mDownButtonPressed {false}
int mDownButtonScrollAmount {10}
bool mHBarVisible {false}
int mHorizontalMarkerDragOffset {0}
ScrollPolicy mHPolicy {ScrollPolicy::ShowAuto}
int mHScroll {0}
bool mIsHorizontalMarkerDragged {false}
bool mIsVerticalMarkerDragged {false}
bool mLeftButtonPressed {false}
int mLeftButtonScrollAmount {10}
bool mOpaque {true}
bool mRightButtonPressed {false}
int mRightButtonScrollAmount {10}
int mScrollbarWidth {12}
bool mUpButtonPressed {false}
int mUpButtonScrollAmount {10}
bool mVBarVisible {false}
int mVerticalMarkerDragOffset {0}
ScrollPolicy mVPolicy {ScrollPolicy::ShowAuto}
int mVScroll {0}
Protected Attributes inherited from fcn::Widget
std::string mActionEventId
std::list< ActionListener * > mActionListeners
Color mBackgroundColor {0xf9fafb}
Color mBaseColor {0xe5e7eb}
Color mBorderColor {0xd1d5db}
unsigned int mBorderSize {0}
std::list< Widget * > mChildren
Font * mCurrentFont {nullptr}
std::list< DeathListener * > mDeathListeners
Rectangle mDimension
bool mEnabled {true}
Size mFixedSize {-1, -1}
bool mFixedSizeUsed {false}
bool mFocusable {false}
FocusHandler * mFocusHandler {nullptr}
std::list< FocusListener * > mFocusListeners
Color mForegroundColor {0x1f2933}
bool mHExpand {false}
std::string mId
FocusHandler * mInternalFocusHandler {nullptr}
std::list< KeyListener * > mKeyListeners
int mLastX {0}
int mLastY {0}
int mMarginBottom {0}
int mMarginLeft {0}
int mMarginRight {0}
int mMarginTop {0}
Size mMaxSize {std::numeric_limits<int>::max(), std::numeric_limits<int>::max()}
Size mMinSize {0, 0}
std::list< MouseListener * > mMouseListeners
Rectangle mOffsetRect
Color mOutlineColor {0x9ca3af}
unsigned int mOutlineSize {0}
unsigned int mPaddingBottom {0}
unsigned int mPaddingLeft {0}
unsigned int mPaddingRight {0}
unsigned int mPaddingTop {0}
Widget * mParent {nullptr}
Color mSelectionColor {0x3b82f6}
SelectionMode mSelectionMode {SelectionMode::None}
bool mTabIn {true}
bool mTabOut {true}
bool mVExpand {false}
bool mVisible {true}
std::list< WidgetListener * > mWidgetListeners
Additional Inherited Members
Static Public Member Functions inherited from fcn::Widget
static DeathListener * _getGuiDeathListener ()
static VisibilityEventHandler * _getVisibilityEventHandler ()
static void _setGuiDeathListener (DeathListener *deathListener)
static void _setVisibilityEventHandler (VisibilityEventHandler *visibilityEventHandler)
static void setGlobalFont (Font *font)
static bool widgetExists (Widget const *widget)
Static Protected Attributes inherited from fcn::Widget
static DefaultFont mDefaultFont
static Font * mGlobalFont = nullptr
static DeathListener * mGuiDeathListener = nullptr
static VisibilityEventHandler * mVisibilityEventHandler = nullptr
static std::list< Widget * > mWidgetInstances
Detailed Description
A scrollable viewport for viewing widgets larger than the visible area.
Implementation if a scrollable area used to view widgets larger than the scroll area. A scroll area can be customized to always show scroll bars or to show them only when necessary.
Definition at line 25 of file scrollarea.hpp.
Member Enumeration Documentation
ScrollPolicy
enum class fcn::ScrollArea::ScrollPolicy : uint8_t strong
Scroll policies for the horizontal and vertical scrollbar.
The policies are:
SHOW_ALWAYS - Always show the scrollbars no matter what. SHOW_NEVER - Never show the scrollbars no matter what. SHOW_AUTO - Show the scrollbars only when needed. That is if the content grows larger then the ScrollArea.
Definition at line 37 of file scrollarea.hpp.
Constructor & Destructor Documentation
ScrollArea() [1/3]
fcn::ScrollArea::ScrollArea ()
Definition at line 14 of file scrollarea.cpp.
ScrollArea() [2/3]
fcn::ScrollArea::ScrollArea (Widget * content) explicit
Constructor.
Parameters
content The content of the scroll area.
Definition at line 19 of file scrollarea.cpp.
References fcn::Widget::addMouseListener(), setContent(), and fcn::Widget::Widget().
ScrollArea() [3/3]
fcn::ScrollArea::ScrollArea (Widget * content, ScrollPolicy hPolicy, ScrollPolicy vPolicy)
Constructor.
Parameters
content The content of the scroll area.
hPolicy The policy for the horizontal scrollbar. See enum with policies.
vPolicy The policy for the vertical scrollbar. See enum with policies.
Definition at line 25 of file scrollarea.cpp.
References fcn::Widget::addMouseListener(), setContent(), and fcn::Widget::Widget().
~ScrollArea()
fcn::ScrollArea::~ScrollArea () override
Definition at line 31 of file scrollarea.cpp.
Member Function Documentation
adjustSize()
void fcn::ScrollArea::adjustSize () override virtual
Resizes the widget's size to fit the content exactly.
Reimplemented from fcn::Widget.
Definition at line 1009 of file scrollarea.cpp.
References fcn::Widget::adjustSize(), getContent(), fcn::Size::getHeight(), fcn::Widget::getMinSize(), fcn::Size::getWidth(), setHeight(), setWidth(), and fcn::Widget::Widget().
checkPolicies()
void fcn::ScrollArea::checkPolicies () protected virtual
Checks the policies for the scroll bars.
Definition at line 635 of file scrollarea.cpp.
References getContent(), fcn::Widget::getHeight(), fcn::Widget::getWidth(), mHBarVisible, mHPolicy, mScrollbarWidth, mVBarVisible, and mVPolicy.
Referenced by expandContent(), getHorizontalMaxScroll(), getVerticalMaxScroll(), logic(), setContent(), setDimension(), setHeight(), setHorizontalScrollPolicy(), setScrollPolicy(), setVerticalScrollPolicy(), and setWidth().
draw()
void fcn::ScrollArea::draw (Graphics * graphics) override virtual
Draws the widget.
The call to draw is initiated by the widget's parent. The graphics object is set up so that all drawing is relative to the widget, i.e coordinate (0,0) is the top left corner of the widget. It is not possible to draw outside of a widget's dimension. If a widget has children, the parent's draw function will always be called before the children's draw functions are called.
NOTE: A widget with children won't draw its children unless the children area given by Widget::getChildrenArea returns a none empty rectangle inside the widgets dimension. The children area is considered relative to the widget's position.
Parameters
Graphics & Rendering A graphics object to draw with.
See also
getChildrenArea, drawOutline, drawBorder
Implements fcn::Widget.
Definition at line 273 of file scrollarea.cpp.
References drawBackground(), drawDownButton(), drawHBar(), drawHMarker(), drawLeftButton(), drawRightButton(), drawUpButton(), drawVBar(), drawVMarker(), fcn::Graphics::fillRectangle(), fcn::Widget::getBaseColor(), fcn::Widget::getHeight(), fcn::Widget::getWidth(), mHBarVisible, mScrollbarWidth, mVBarVisible, and fcn::Graphics::setColor().
drawBackground()
void fcn::ScrollArea::drawBackground (Graphics * graphics) protected virtual
Draws the background of the scroll area, that is the area behind the content.
Parameters
Graphics & Rendering a Graphics object to draw with.
Definition at line 340 of file scrollarea.cpp.
References fcn::Graphics::fillRectangle(), fcn::Widget::getBackgroundColor(), getChildrenArea(), isOpaque(), and fcn::Graphics::setColor().
Referenced by draw().
drawDownButton()
void fcn::ScrollArea::drawDownButton (Graphics * graphics) protected virtual
Draws the down button.
Parameters
Graphics & Rendering a Graphics object to draw with.
Definition at line 403 of file scrollarea.cpp.
References fcn::Color::a, fcn::Graphics::drawLine(), fcn::Graphics::fillRectangle(), fcn::Widget::getBaseColor(), getDownButtonDimension(), fcn::Widget::getForegroundColor(), fcn::Rectangle::height, mDownButtonPressed, fcn::Graphics::popClipArea(), fcn::Graphics::pushClipArea(), fcn::Graphics::setColor(), and fcn::Rectangle::width.
Referenced by draw().
drawHBar()
void fcn::ScrollArea::drawHBar (Graphics * graphics) protected virtual
Draws the horizontal scroll bar.
Parameters
Graphics & Rendering a Graphics object to draw with.
Definition at line 298 of file scrollarea.cpp.
References fcn::Color::a, fcn::Graphics::drawLine(), fcn::Graphics::fillRectangle(), fcn::Widget::getBaseColor(), getHorizontalBarDimension(), fcn::Rectangle::height, fcn::Graphics::popClipArea(), fcn::Graphics::pushClipArea(), fcn::Graphics::setColor(), and fcn::Rectangle::width.
Referenced by draw().
drawHMarker()
void fcn::ScrollArea::drawHMarker (Graphics * graphics) protected virtual
Draws the horizontal marker.
Parameters
Graphics & Rendering a Graphics object to draw with.
Definition at line 594 of file scrollarea.cpp.
References fcn::Color::a, fcn::Graphics::drawLine(), fcn::Graphics::fillRectangle(), fcn::Widget::getBaseColor(), getHorizontalMarkerDimension(), fcn::Rectangle::height, fcn::Graphics::popClipArea(), fcn::Graphics::pushClipArea(), fcn::Graphics::setColor(), and fcn::Rectangle::width.
Referenced by draw().
drawLeftButton()
void fcn::ScrollArea::drawLeftButton (Graphics * graphics) protected virtual
Draws the left button.
Parameters
Graphics & Rendering a Graphics object to draw with.
Definition at line 458 of file scrollarea.cpp.
References fcn::Color::a, fcn::Graphics::drawLine(), fcn::Graphics::fillRectangle(), fcn::Widget::getBaseColor(), fcn::Widget::getForegroundColor(), getLeftButtonDimension(), fcn::Rectangle::height, mLeftButtonPressed, fcn::Graphics::popClipArea(), fcn::Graphics::pushClipArea(), fcn::Graphics::setColor(), and fcn::Rectangle::width.
Referenced by draw().
drawRightButton()
void fcn::ScrollArea::drawRightButton (Graphics * graphics) protected virtual
Draws the right button.
Parameters
Graphics & Rendering a Graphics object to draw with.
Definition at line 512 of file scrollarea.cpp.
References fcn::Color::a, fcn::Graphics::drawLine(), fcn::Graphics::fillRectangle(), fcn::Widget::getBaseColor(), fcn::Widget::getForegroundColor(), getRightButtonDimension(), fcn::Rectangle::height, mRightButtonPressed, fcn::Graphics::popClipArea(), fcn::Graphics::pushClipArea(), fcn::Graphics::setColor(), and fcn::Rectangle::width.
Referenced by draw().
drawUpButton()
void fcn::ScrollArea::drawUpButton (Graphics * graphics) protected virtual
Draws the up button.
Parameters
Graphics & Rendering a Graphics object to draw with.
Definition at line 348 of file scrollarea.cpp.
References fcn::Color::a, fcn::Graphics::drawLine(), fcn::Graphics::fillRectangle(), fcn::Widget::getBaseColor(), fcn::Widget::getForegroundColor(), getUpButtonDimension(), fcn::Rectangle::height, mUpButtonPressed, fcn::Graphics::popClipArea(), fcn::Graphics::pushClipArea(), fcn::Graphics::setColor(), and fcn::Rectangle::width.
Referenced by draw().
drawVBar()
void fcn::ScrollArea::drawVBar (Graphics * graphics) protected virtual
Draws the vertical scroll bar.
Parameters
Graphics & Rendering a Graphics object to draw with.
Definition at line 319 of file scrollarea.cpp.
References fcn::Color::a, fcn::Graphics::drawLine(), fcn::Graphics::fillRectangle(), fcn::Widget::getBaseColor(), getVerticalBarDimension(), fcn::Rectangle::height, fcn::Graphics::popClipArea(), fcn::Graphics::pushClipArea(), fcn::Graphics::setColor(), and fcn::Rectangle::width.
Referenced by draw().
drawVMarker()
void fcn::ScrollArea::drawVMarker (Graphics * graphics) protected virtual
Draws the vertical marker.
Parameters
Graphics & Rendering a Graphics object to draw with.
Definition at line 567 of file scrollarea.cpp.
References fcn::Color::a, fcn::Graphics::drawLine(), fcn::Graphics::fillRectangle(), fcn::Widget::getBaseColor(), getVerticalMarkerDimension(), fcn::Rectangle::height, fcn::Graphics::popClipArea(), fcn::Graphics::pushClipArea(), fcn::Graphics::setColor(), and fcn::Rectangle::width.
Referenced by draw().
expandContent() [1/2]
void fcn::Widget::expandContent () inline
Expands the child widgets to the size of this widget, calls recursively all childs.
This is a convenience wrapper that calls expandContent(true).
Definition at line 1440 of file widget.hpp.
expandContent() [2/2]
void fcn::ScrollArea::expandContent (bool recursion) override virtual
Expands child widgets to fit this widget's size.
Parameters
recursion If true, call expandContent recursively on children.
Reimplemented from fcn::Widget.
Definition at line 1020 of file scrollarea.cpp.
References checkPolicies(), fcn::Widget::expandContent(), getContent(), fcn::Widget::getHeight(), fcn::Widget::getWidth(), setHeight(), setWidth(), and fcn::Widget::Widget().
getChildrenArea()
Rectangle fcn::ScrollArea::getChildrenArea () override virtual
Gets the area of the widget occupied by the widget's children.
By default this method returns an empty rectangle as not all widgets are containers. If you want to make a container this method should return the area where the children resides. This method is used when drawing children of a widget when computing clip rectangles for the children.
NOTE: The returned rectangle should be relative to the widget, i.e a rectangle with x and y coordinate (0,0) and with width and height the same as the widget will let the children draw themselves in the whole widget.
An example of a widget that overloads this method is ScrollArea. A ScrollArea has a view of its constant and that view is the children area. The size of a ScrollArea's children area might vary depending on if the scroll bars of the ScrollArea is shown or not.
Returns
The area of the widget occupied by the widget's children.
Reimplemented from fcn::Widget.
Definition at line 760 of file scrollarea.cpp.
References fcn::Widget::getHeight(), fcn::Widget::getWidth(), fcn::Rectangle::isEmpty(), mHBarVisible, mScrollbarWidth, and mVBarVisible.
Referenced by drawBackground(), getHorizontalMarkerDimension(), getHorizontalMaxScroll(), getVerticalMarkerDimension(), getVerticalMaxScroll(), getWidgetAt(), mousePressed(), mouseWheelMovedDown(), mouseWheelMovedLeft(), mouseWheelMovedRight(), and mouseWheelMovedUp().
getContent()
Widget * fcn::ScrollArea::getContent () const
Gets the content.
Returns
The content of the scroll area.
Definition at line 52 of file scrollarea.cpp.
References fcn::Widget::mChildren, and fcn::Widget::Widget().
Referenced by adjustSize(), checkPolicies(), expandContent(), getHorizontalMarkerDimension(), getHorizontalMaxScroll(), getVerticalMarkerDimension(), getVerticalMaxScroll(), getWidgetAt(), logic(), resizeToContent(), setDimension(), setHeight(), setWidth(), and showWidgetPart().
getDownButtonDimension()
Rectangle fcn::ScrollArea::getDownButtonDimension () protected
Gets the down button dimension.
Returns
the dimension of the down button.
Definition at line 723 of file scrollarea.cpp.
References fcn::Widget::getHeight(), fcn::Widget::getWidth(), mHBarVisible, mScrollbarWidth, and mVBarVisible.
Referenced by drawDownButton(), getVerticalBarDimension(), and mousePressed().
getDownButtonScrollAmount()
int fcn::ScrollArea::getDownButtonScrollAmount () const
Gets the amount to scroll in pixels when the down scroll button is pushed.
Returns
The amount to scroll in pixels.
See also
setDownButtonScrollAmount
Definition at line 1069 of file scrollarea.cpp.
References mDownButtonScrollAmount.
getHorizontalBarDimension()
Rectangle fcn::ScrollArea::getHorizontalBarDimension () protected
Gets the horizontal scrollbar dimension.
Returns
the dimension of the horizontal scrollbar.
Definition at line 796 of file scrollarea.cpp.
References fcn::Widget::getHeight(), getLeftButtonDimension(), getRightButtonDimension(), fcn::Widget::getWidth(), mHBarVisible, mScrollbarWidth, mVBarVisible, and fcn::Rectangle::width.
Referenced by drawHBar(), getHorizontalMarkerDimension(), mouseDragged(), and mousePressed().
getHorizontalMarkerDimension()
Rectangle fcn::ScrollArea::getHorizontalMarkerDimension () protected
Gets the horizontal marker dimension.
Returns
the dimension of the horizontal marker.
Definition at line 847 of file scrollarea.cpp.
References getChildrenArea(), getContent(), getHorizontalBarDimension(), getHorizontalMaxScroll(), getHorizontalScrollAmount(), fcn::Widget::getWidth(), mHBarVisible, mScrollbarWidth, fcn::Rectangle::width, fcn::Rectangle::x, and fcn::Rectangle::y.
Referenced by drawHMarker(), mouseDragged(), and mousePressed().
getHorizontalMaxScroll()
int fcn::ScrollArea::getHorizontalMaxScroll ()
Gets the maximum amount of horizontal scroll.
Returns
The horizontal max scroll.
Definition at line 134 of file scrollarea.cpp.
References checkPolicies(), fcn::Widget::getBorderSize(), getChildrenArea(), getContent(), fcn::Widget::getWidth(), and fcn::Rectangle::width.
Referenced by getHorizontalMarkerDimension(), mouseDragged(), and setHorizontalScrollAmount().
getHorizontalScrollAmount()
int fcn::ScrollArea::getHorizontalScrollAmount () const
Gets the amount that is scrolled horizontally.
Returns
The scroll amount on horizontal scroll.
See also
setHorizontalScrollAmount, setScrollAmount
Definition at line 123 of file scrollarea.cpp.
References mHScroll.
Referenced by getHorizontalMarkerDimension(), logic(), mousePressed(), mouseWheelMovedLeft(), and mouseWheelMovedRight().
getHorizontalScrollPolicy()
ScrollArea::ScrollPolicy fcn::ScrollArea::getHorizontalScrollPolicy () const
Gets the horizontal scrollbar policy.
See enum with policies.
Returns
The policy for the horizontal scrollbar policy.
See also
setHorizontalScrollPolicy, setScrollPolicy
Definition at line 67 of file scrollarea.cpp.
References mHPolicy.
getLeftButtonDimension()
Rectangle fcn::ScrollArea::getLeftButtonDimension () protected
Gets the left button dimension.
Returns
the dimension of the left button.
Definition at line 737 of file scrollarea.cpp.
References fcn::Widget::getHeight(), mHBarVisible, and mScrollbarWidth.
Referenced by drawLeftButton(), getHorizontalBarDimension(), and mousePressed().
getLeftButtonScrollAmount()
int fcn::ScrollArea::getLeftButtonScrollAmount () const
Gets the amount to scroll in pixels when the left scroll button is pushed.
Returns
The amount to scroll in pixels.
See also
setLeftButtonScrollAmount
Definition at line 1054 of file scrollarea.cpp.
References mLeftButtonScrollAmount.
getRightButtonDimension()
Rectangle fcn::ScrollArea::getRightButtonDimension () protected
Gets the right button dimension.
Returns
the dimension of the right button.
Definition at line 746 of file scrollarea.cpp.
References fcn::Widget::getHeight(), fcn::Widget::getWidth(), mHBarVisible, mScrollbarWidth, and mVBarVisible.
Referenced by drawRightButton(), getHorizontalBarDimension(), and mousePressed().
getRightButtonScrollAmount()
int fcn::ScrollArea::getRightButtonScrollAmount () const
Gets the amount to scroll in pixels when the right scroll button is pushed.
Returns
The amount to scroll in pixels.
See also
setRightButtonScrollAmount
Definition at line 1059 of file scrollarea.cpp.
References mRightButtonScrollAmount.
getScrollbarWidth()
int fcn::ScrollArea::getScrollbarWidth () const
Gets the width of the scroll bars.
Returns
the width of the ScrollBar.
See also
setScrollbarWidth
Definition at line 179 of file scrollarea.cpp.
References mScrollbarWidth.
getUpButtonDimension()
Rectangle fcn::ScrollArea::getUpButtonDimension () protected
Gets the up button dimension.
Returns
the dimension of the up button.
Definition at line 714 of file scrollarea.cpp.
References fcn::Widget::getWidth(), mScrollbarWidth, and mVBarVisible.
Referenced by drawUpButton(), getVerticalBarDimension(), and mousePressed().
getUpButtonScrollAmount()
int fcn::ScrollArea::getUpButtonScrollAmount () const
Gets the amount to scroll in pixels when the up scroll button is pushed.
Returns
The amount to scroll in pixels.
See also
setUpButtonScrollAmount
Definition at line 1064 of file scrollarea.cpp.
References mUpButtonScrollAmount.
getVerticalBarDimension()
Rectangle fcn::ScrollArea::getVerticalBarDimension () protected
Gets the vertical scrollbar dimension.
Returns
the dimension of the vertical scrollbar.
Definition at line 775 of file scrollarea.cpp.
References getDownButtonDimension(), fcn::Widget::getHeight(), getUpButtonDimension(), fcn::Widget::getWidth(), fcn::Rectangle::height, mHBarVisible, mScrollbarWidth, and mVBarVisible.
Referenced by drawVBar(), getVerticalMarkerDimension(), mouseDragged(), and mousePressed().
getVerticalMarkerDimension()
Rectangle fcn::ScrollArea::getVerticalMarkerDimension () protected
Gets the vertical marker dimension.
Returns
the dimension of the vertical marker.
Definition at line 817 of file scrollarea.cpp.
References getChildrenArea(), getContent(), fcn::Widget::getHeight(), getVerticalBarDimension(), getVerticalMaxScroll(), getVerticalScrollAmount(), fcn::Rectangle::height, mScrollbarWidth, mVBarVisible, fcn::Rectangle::x, and fcn::Rectangle::y.
Referenced by drawVMarker(), mouseDragged(), and mousePressed().
getVerticalMaxScroll()
int fcn::ScrollArea::getVerticalMaxScroll ()
Gets the maximum amount of vertical scroll.
Returns
The vertical max scroll.
Definition at line 151 of file scrollarea.cpp.
References checkPolicies(), fcn::Widget::getBorderSize(), getChildrenArea(), getContent(), fcn::Widget::getHeight(), and fcn::Rectangle::height.
Referenced by getVerticalMarkerDimension(), mouseDragged(), and setVerticalScrollAmount().
getVerticalScrollAmount()
int fcn::ScrollArea::getVerticalScrollAmount () const
Gets the amount that is scrolled vertically.
Returns
The scroll amount on vertical scroll.
See also
setVerticalScrollAmount, setScrollAmount
Definition at line 105 of file scrollarea.cpp.
References mVScroll.
Referenced by getVerticalMarkerDimension(), logic(), mousePressed(), mouseWheelMovedDown(), and mouseWheelMovedUp().
getVerticalScrollPolicy()
ScrollArea::ScrollPolicy fcn::ScrollArea::getVerticalScrollPolicy () const
Gets the vertical scrollbar policy.
See enum with policies.
Returns
The policy for the vertical scrollbar.
See also
setVerticalScrollPolicy, setScrollPolicy
Definition at line 78 of file scrollarea.cpp.
References mVPolicy.
getWidgetAt()
Widget * fcn::ScrollArea::getWidgetAt (int x, int y) virtual
Hit-test for widgets inside the scroll area.
Parameters
x X coordinate to test (local).
y Y coordinate to test (local).
Returns
The widget at (x,y) or nullptr if none.
Definition at line 889 of file scrollarea.cpp.
References getChildrenArea(), getContent(), and fcn::Widget::Widget().
isOpaque()
bool fcn::ScrollArea::isOpaque () const
Checks if the scroll area is opaque, that is if the scroll area displays its background.
Returns
True if the scroll area is opaque, false otherwise.
Definition at line 1079 of file scrollarea.cpp.
References mOpaque.
Referenced by drawBackground().
logic()
void fcn::ScrollArea::logic () override virtual
Called for all widgets in the gui each time Gui::logic is called.
You can do logic stuff here like playing an animation.
See also
Gui::logic
Reimplemented from fcn::Widget.
Definition at line 621 of file scrollarea.cpp.
References checkPolicies(), fcn::Widget::getBorderSize(), getContent(), getHorizontalScrollAmount(), getVerticalScrollAmount(), fcn::Widget::logic(), mHScroll, mVScroll, setHorizontalScrollAmount(), fcn::Widget::setPosition(), and setVerticalScrollAmount().
mouseDragged()
void fcn::ScrollArea::mouseDragged (MouseEvent & mouseEvent) override virtual
Called when the mouse has moved and the mouse has previously been pressed on the widget.
Parameters
mouseEvent Describes the event.
Reimplemented from fcn::MouseListener.
Definition at line 242 of file scrollarea.cpp.
References fcn::InputEvent::consume(), getHorizontalBarDimension(), getHorizontalMarkerDimension(), getHorizontalMaxScroll(), getVerticalBarDimension(), getVerticalMarkerDimension(), getVerticalMaxScroll(), fcn::MouseEvent::getX(), fcn::MouseEvent::getY(), fcn::Rectangle::height, mHorizontalMarkerDragOffset, mIsHorizontalMarkerDragged, mIsVerticalMarkerDragged, mVerticalMarkerDragOffset, setHorizontalScrollAmount(), setVerticalScrollAmount(), fcn::Rectangle::width, fcn::Rectangle::x, and fcn::Rectangle::y.
mousePressed()
void fcn::ScrollArea::mousePressed (MouseEvent & mouseEvent) override virtual
Called when a mouse button has been pressed on the widget area.
NOTE: A mouse press is NOT equal to a mouse click. Use mouseClickMessage to check for mouse clicks.
Parameters
mouseEvent Describes the event.
Reimplemented from fcn::MouseListener.
Definition at line 184 of file scrollarea.cpp.
References getChildrenArea(), getDownButtonDimension(), getHorizontalBarDimension(), getHorizontalMarkerDimension(), getHorizontalScrollAmount(), getLeftButtonDimension(), getRightButtonDimension(), getUpButtonDimension(), getVerticalBarDimension(), getVerticalMarkerDimension(), getVerticalScrollAmount(), fcn::MouseEvent::getX(), fcn::MouseEvent::getY(), mDownButtonPressed, mDownButtonScrollAmount, mHorizontalMarkerDragOffset, mIsHorizontalMarkerDragged, mIsVerticalMarkerDragged, mLeftButtonPressed, mLeftButtonScrollAmount, mRightButtonPressed, mRightButtonScrollAmount, mUpButtonPressed, mUpButtonScrollAmount, mVerticalMarkerDragOffset, setHorizontalScrollAmount(), setVerticalScrollAmount(), fcn::Rectangle::x, and fcn::Rectangle::y.
mouseReleased()
void fcn::ScrollArea::mouseReleased (MouseEvent & mouseEvent) override virtual
Called when a mouse button has been released on the widget area.
Parameters
mouseEvent Describes the event.
Reimplemented from fcn::MouseListener.
Definition at line 230 of file scrollarea.cpp.
References fcn::InputEvent::consume(), mDownButtonPressed, mIsHorizontalMarkerDragged, mIsVerticalMarkerDragged, mLeftButtonPressed, mRightButtonPressed, and mUpButtonPressed.
mouseWheelMovedDown()
void fcn::ScrollArea::mouseWheelMovedDown (MouseEvent & mouseEvent) override virtual
Called when the mouse wheel has moved down on the widget area.
Parameters
mouseEvent Describes the event.
Reimplemented from fcn::MouseListener.
Definition at line 914 of file scrollarea.cpp.
References fcn::InputEvent::consume(), getChildrenArea(), getVerticalScrollAmount(), fcn::InputEvent::isConsumed(), mVBarVisible, and setVerticalScrollAmount().
mouseWheelMovedLeft()
void fcn::ScrollArea::mouseWheelMovedLeft (MouseEvent & mouseEvent) override virtual
Called when the mouse wheel has moved left on the widget area.
Parameters
mouseEvent Describes the event.
Reimplemented from fcn::MouseListener.
Definition at line 946 of file scrollarea.cpp.
References fcn::InputEvent::consume(), getChildrenArea(), getHorizontalScrollAmount(), fcn::InputEvent::isConsumed(), mHBarVisible, and setHorizontalScrollAmount().
mouseWheelMovedRight()
void fcn::ScrollArea::mouseWheelMovedRight (MouseEvent & mouseEvent) override virtual
Called when the mouse wheel has moved right on the widget area.
Parameters
mouseEvent Describes the event.
Reimplemented from fcn::MouseListener.
Definition at line 930 of file scrollarea.cpp.
References fcn::InputEvent::consume(), getChildrenArea(), getHorizontalScrollAmount(), fcn::InputEvent::isConsumed(), mHBarVisible, and setHorizontalScrollAmount().
mouseWheelMovedUp()
void fcn::ScrollArea::mouseWheelMovedUp (MouseEvent & mouseEvent) override virtual
Called when the mouse wheel has moved up on the widget area.
Parameters
mouseEvent Describes the event.
Reimplemented from fcn::MouseListener.
Definition at line 898 of file scrollarea.cpp.
References fcn::InputEvent::consume(), getChildrenArea(), getVerticalScrollAmount(), fcn::InputEvent::isConsumed(), mVBarVisible, and setVerticalScrollAmount().
resizeToContent() [1/2]
void fcn::Widget::resizeToContent () inline
Resizes the widget's size to fit the content exactly, calls recursively all childs.
This is a convenience wrapper that calls resizeToContent(true).
Definition at line 1417 of file widget.hpp.
resizeToContent() [2/2]
void fcn::ScrollArea::resizeToContent (bool recursion) override virtual
Resize this widget to fit its content.
Parameters
recursion If true, perform the resize operation recursively on children.
Reimplemented from fcn::Widget.
Definition at line 997 of file scrollarea.cpp.
References getContent(), fcn::Size::getHeight(), fcn::Widget::getMinSize(), fcn::Size::getWidth(), fcn::Widget::resizeToContent(), setHeight(), setWidth(), and fcn::Widget::Widget().
setContent()
void fcn::ScrollArea::setContent (Widget * widget)
Sets the content.
Parameters
widget The content of the scroll area.
Definition at line 40 of file scrollarea.cpp.
References fcn::Widget::add(), checkPolicies(), fcn::Widget::removeAllChildren(), fcn::Widget::setPosition(), and fcn::Widget::Widget().
Referenced by ScrollArea(), and ScrollArea().
setDimension()
void fcn::ScrollArea::setDimension (Rectangle const & dimension)
Set the bounds/dimension of the scroll area.
Definition at line 984 of file scrollarea.cpp.
References checkPolicies(), getContent(), fcn::Widget::getHeight(), fcn::Widget::getWidth(), fcn::Widget::setDimension(), fcn::Widget::setHeight(), fcn::Widget::setWidth(), and fcn::Widget::Widget().
setDownButtonScrollAmount()
void fcn::ScrollArea::setDownButtonScrollAmount (int amount)
Sets the amount to scroll in pixels when the down scroll button is pushed.
Parameters
amount The amount to scroll in pixels.
See also
getDownButtonScrollAmount
Definition at line 1049 of file scrollarea.cpp.
References mDownButtonScrollAmount.
setHeight()
void fcn::ScrollArea::setHeight (int height)
Set the height of the scroll area.
Definition at line 973 of file scrollarea.cpp.
References checkPolicies(), getContent(), fcn::Widget::getHeight(), fcn::Widget::setHeight(), and fcn::Widget::Widget().
Referenced by adjustSize(), expandContent(), and resizeToContent().
setHorizontalScrollAmount()
void fcn::ScrollArea::setHorizontalScrollAmount (int hScroll)
Sets the amount to scroll horizontally.
Parameters
hScroll The amount to scroll.
See also
getHorizontalScrollAmount
Definition at line 110 of file scrollarea.cpp.
References getHorizontalMaxScroll(), and mHScroll.
Referenced by logic(), mouseDragged(), mousePressed(), mouseWheelMovedLeft(), mouseWheelMovedRight(), setScrollAmount(), and showWidgetPart().
setHorizontalScrollPolicy()
void fcn::ScrollArea::setHorizontalScrollPolicy (ScrollPolicy hPolicy)
Sets the horizontal scrollbar policy.
See enum with policies.
Parameters
hPolicy The policy for the horizontal scrollbar.
See also
getHorizontalScrollPolicy
Definition at line 61 of file scrollarea.cpp.
References checkPolicies(), and mHPolicy.
setLeftButtonScrollAmount()
void fcn::ScrollArea::setLeftButtonScrollAmount (int amount)
Sets the amount to scroll in pixels when the left scroll button is pushed.
Parameters
amount The amount to scroll in pixels.
See also
getLeftButtonScrollAmount
Definition at line 1034 of file scrollarea.cpp.
References mLeftButtonScrollAmount.
setOpaque()
void fcn::ScrollArea::setOpaque (bool opaque)
Sets the scroll area to be opaque, that is sets the scroll area to display its background.
Parameters
opaque True if the scroll area should be opaque, false otherwise.
Definition at line 1074 of file scrollarea.cpp.
References mOpaque.
setRightButtonScrollAmount()
void fcn::ScrollArea::setRightButtonScrollAmount (int amount)
Sets the amount to scroll in pixels when the right scroll button is pushed.
Parameters
amount The amount to scroll in pixels.
See also
getRightButtonScrollAmount
Definition at line 1039 of file scrollarea.cpp.
References mRightButtonScrollAmount.
setScrollAmount()
void fcn::ScrollArea::setScrollAmount (int hScroll, int vScroll)
Sets the amount to scroll horizontally and vertically.
Parameters
hScroll The amount to scroll on horizontal scroll.
vScroll The amount to scroll on vertical scroll.
See also
getHorizontalScrollAmount, getVerticalScrollAmount
Definition at line 128 of file scrollarea.cpp.
References setHorizontalScrollAmount(), and setVerticalScrollAmount().
setScrollbarWidth()
void fcn::ScrollArea::setScrollbarWidth (int width)
Sets the width of the scroll bars.
Parameters
width The width of the scroll bars.
See also
getScrollbarWidth
Definition at line 170 of file scrollarea.cpp.
References mScrollbarWidth.
setScrollPolicy()
void fcn::ScrollArea::setScrollPolicy (ScrollPolicy hPolicy, ScrollPolicy vPolicy)
Sets the horizontal and vertical scrollbar policy.
Parameters
hPolicy The policy for the horizontal scrollbar.
vPolicy The policy for the vertical scrollbar.
See also
getVerticalScrollPolicy, getHorizontalScrollPolicy
Definition at line 83 of file scrollarea.cpp.
References checkPolicies(), mHPolicy, and mVPolicy.
setUpButtonScrollAmount()
void fcn::ScrollArea::setUpButtonScrollAmount (int amount)
Sets the amount to scroll in pixels when the up scroll button is pushed.
Parameters
amount The amount to scroll in pixels.
See also
getUpButtonScrollAmount
Definition at line 1044 of file scrollarea.cpp.
References mUpButtonScrollAmount.
setVerticalScrollAmount()
void fcn::ScrollArea::setVerticalScrollAmount (int vScroll)
Sets the amount to scroll vertically.
Parameters
vScroll The amount to scroll.
See also
getVerticalScrollAmount
Definition at line 90 of file scrollarea.cpp.
References getVerticalMaxScroll(), and mVScroll.
Referenced by logic(), mouseDragged(), mousePressed(), mouseWheelMovedDown(), mouseWheelMovedUp(), setScrollAmount(), and showWidgetPart().
setVerticalScrollPolicy()
void fcn::ScrollArea::setVerticalScrollPolicy (ScrollPolicy vPolicy)
Sets the vertical scrollbar policy.
See enum with policies.
Parameters
vPolicy The policy for the vertical scrollbar.
See also
getVerticalScrollPolicy
Definition at line 72 of file scrollarea.cpp.
References checkPolicies(), and mVPolicy.
setWidth()
void fcn::ScrollArea::setWidth (int width)
Set the width of the scroll area.
Definition at line 962 of file scrollarea.cpp.
References checkPolicies(), getContent(), fcn::Widget::getWidth(), fcn::Widget::setWidth(), and fcn::Widget::Widget().
Referenced by adjustSize(), expandContent(), and resizeToContent().
showWidgetPart()
void fcn::ScrollArea::showWidgetPart (Widget * widget, Rectangle area) override virtual
Tries to show a specific part of a widget by moving it.
Used if the widget should act as a container.
Parameters
widget The target widget.
area The area to show.
Reimplemented from fcn::Widget.
Definition at line 877 of file scrollarea.cpp.
References fcn::Widget::getBorderSize(), getContent(), fcn::Widget::getX(), fcn::Widget::getY(), setHorizontalScrollAmount(), setVerticalScrollAmount(), fcn::Widget::showWidgetPart(), and fcn::Widget::Widget().
Member Data Documentation
mDownButtonPressed
bool fcn::ScrollArea::mDownButtonPressed {false} protected
True if the down button is pressed, false otherwise.
Definition at line 508 of file scrollarea.hpp.
Referenced by drawDownButton(), mousePressed(), and mouseReleased().
mDownButtonScrollAmount
int fcn::ScrollArea::mDownButtonScrollAmount {10} protected
Holds the down button scroll amount.
Definition at line 528 of file scrollarea.hpp.
Referenced by getDownButtonScrollAmount(), mousePressed(), and setDownButtonScrollAmount().
mHBarVisible
bool fcn::ScrollArea::mHBarVisible {false} protected
True if the horizontal scroll bar is visible, false otherwise.
Definition at line 498 of file scrollarea.hpp.
Referenced by checkPolicies(), draw(), getChildrenArea(), getDownButtonDimension(), getHorizontalBarDimension(), getHorizontalMarkerDimension(), getLeftButtonDimension(), getRightButtonDimension(), getVerticalBarDimension(), mouseWheelMovedLeft(), and mouseWheelMovedRight().
mHorizontalMarkerDragOffset
int fcn::ScrollArea::mHorizontalMarkerDragOffset {0} protected
Holds the horizontal markers drag offset.
Definition at line 553 of file scrollarea.hpp.
Referenced by mouseDragged(), and mousePressed().
mHPolicy
ScrollPolicy fcn::ScrollArea::mHPolicy {ScrollPolicy::ShowAuto} protected
Holds the horizontal scroll bar policy.
Definition at line 483 of file scrollarea.hpp.
Referenced by checkPolicies(), getHorizontalScrollPolicy(), setHorizontalScrollPolicy(), and setScrollPolicy().
mHScroll
int fcn::ScrollArea::mHScroll {0} protected
Holds the horizontal scroll amount.
Definition at line 473 of file scrollarea.hpp.
Referenced by getHorizontalScrollAmount(), logic(), and setHorizontalScrollAmount().
mIsHorizontalMarkerDragged
bool fcn::ScrollArea::mIsHorizontalMarkerDragged {false} protected
True if the horizontal marked is dragged.
Definition at line 548 of file scrollarea.hpp.
Referenced by mouseDragged(), mousePressed(), and mouseReleased().
mIsVerticalMarkerDragged
bool fcn::ScrollArea::mIsVerticalMarkerDragged {false} protected
True if the vertical marked is dragged.
Definition at line 543 of file scrollarea.hpp.
Referenced by mouseDragged(), mousePressed(), and mouseReleased().
mLeftButtonPressed
bool fcn::ScrollArea::mLeftButtonPressed {false} protected
True if the left button is pressed, false otherwise.
Definition at line 513 of file scrollarea.hpp.
Referenced by drawLeftButton(), mousePressed(), and mouseReleased().
mLeftButtonScrollAmount
int fcn::ScrollArea::mLeftButtonScrollAmount {10} protected
Holds the left button scroll amount.
Definition at line 533 of file scrollarea.hpp.
Referenced by getLeftButtonScrollAmount(), mousePressed(), and setLeftButtonScrollAmount().
mOpaque
bool fcn::ScrollArea::mOpaque {true} protected
True if the scroll area should be opaque (that is display its background), false otherwise.
Definition at line 564 of file scrollarea.hpp.
Referenced by isOpaque(), and setOpaque().
mRightButtonPressed
bool fcn::ScrollArea::mRightButtonPressed {false} protected
True if the right button is pressed, false otherwise.
Definition at line 518 of file scrollarea.hpp.
Referenced by drawRightButton(), mousePressed(), and mouseReleased().
mRightButtonScrollAmount
int fcn::ScrollArea::mRightButtonScrollAmount {10} protected
Holds the right button scroll amount.
Definition at line 538 of file scrollarea.hpp.
Referenced by getRightButtonScrollAmount(), mousePressed(), and setRightButtonScrollAmount().
mScrollbarWidth
int fcn::ScrollArea::mScrollbarWidth {12} protected
Holds the width of the scroll bars.
Definition at line 478 of file scrollarea.hpp.
Referenced by checkPolicies(), draw(), getChildrenArea(), getDownButtonDimension(), getHorizontalBarDimension(), getHorizontalMarkerDimension(), getLeftButtonDimension(), getRightButtonDimension(), getScrollbarWidth(), getUpButtonDimension(), getVerticalBarDimension(), getVerticalMarkerDimension(), and setScrollbarWidth().
mUpButtonPressed
bool fcn::ScrollArea::mUpButtonPressed {false} protected
True if the up button is pressed, false otherwise.
Definition at line 503 of file scrollarea.hpp.
Referenced by drawUpButton(), mousePressed(), and mouseReleased().
mUpButtonScrollAmount
int fcn::ScrollArea::mUpButtonScrollAmount {10} protected
Holds the up button scroll amount.
Definition at line 523 of file scrollarea.hpp.
Referenced by getUpButtonScrollAmount(), mousePressed(), and setUpButtonScrollAmount().
mVBarVisible
bool fcn::ScrollArea::mVBarVisible {false} protected
True if the vertical scroll bar is visible, false otherwise.
Definition at line 493 of file scrollarea.hpp.
Referenced by checkPolicies(), draw(), getChildrenArea(), getDownButtonDimension(), getHorizontalBarDimension(), getRightButtonDimension(), getUpButtonDimension(), getVerticalBarDimension(), getVerticalMarkerDimension(), mouseWheelMovedDown(), and mouseWheelMovedUp().
mVerticalMarkerDragOffset
int fcn::ScrollArea::mVerticalMarkerDragOffset {0} protected
Holds the vertical markers drag offset.
Definition at line 558 of file scrollarea.hpp.
Referenced by mouseDragged(), and mousePressed().
mVPolicy
ScrollPolicy fcn::ScrollArea::mVPolicy {ScrollPolicy::ShowAuto} protected
Holds the vertical scroll bar policy.
Definition at line 488 of file scrollarea.hpp.
Referenced by checkPolicies(), getVerticalScrollPolicy(), setScrollPolicy(), and setVerticalScrollPolicy().
mVScroll
int fcn::ScrollArea::mVScroll {0} protected
Holds the vertical scroll amount.
Definition at line 468 of file scrollarea.hpp.
Referenced by getVerticalScrollAmount(), logic(), and setVerticalScrollAmount().
The documentation for this class was generated from the following files:
scrollarea.hpp
scrollarea.cpp