FifeGUI: fcn::Button Class Reference
fcn::Button Class Reference
Widgets
#include <button.hpp>
Public Member Functions
void adjustSize () override
void ancestorHidden (Event const &e) override
Button (Button &&)=delete
Button (Button const &)=delete
Button (std::string caption)
void draw (Graphics *graphics) override
void focusLost (Event const &event) override
void fontChanged () override
Graphics::Alignment getAlignment () const
std::string const & getCaption () const
int getDownXOffset () const
int getDownYOffset () const
bool isActive () const
void keyPressed (KeyEvent &keyEvent) override
void keyReleased (KeyEvent &keyEvent) override
void mouseDragged (MouseEvent &mouseEvent) override
void mouseEntered (MouseEvent &mouseEvent) override
void mouseExited (MouseEvent &mouseEvent) override
void mousePressed (MouseEvent &mouseEvent) override
void mouseReleased (MouseEvent &mouseEvent) override
Button & operator= (Button &&)=delete
Button & operator= (Button const &)=delete
void resizeToContent ()
void resizeToContent (bool recursion) override
void setActive (bool state)
void setAlignment (Graphics::Alignment alignment)
void setCaption (std::string const &caption)
void setDownOffset (int x, int y)
void setDownXOffset (int offset)
void setDownYOffset (int offset)
Public Member Functions inherited from fcn::Widget
virtual void _draw (Graphics *graphics)
virtual FocusHandler * _getFocusHandler ()
virtual std::list< FocusListener * > const & _getFocusListeners ()
virtual FocusHandler * _getInternalFocusHandler ()
virtual std::list< KeyListener * > const & _getKeyListeners ()
virtual std::list< MouseListener * > const & _getMouseListeners ()
virtual void _logic ()
virtual void _setFocusHandler (FocusHandler *focusHandler)
virtual void _setParent (Widget *parent)
void adaptLayout ()
virtual void adaptLayout (bool top)
void addActionListener (ActionListener *actionListener)
void addDeathListener (DeathListener *deathListener)
void addFocusListener (FocusListener *focusListener)
void addKeyListener (KeyListener *keyListener)
void addMouseListener (MouseListener *mouseListener)
void addWidgetListener (WidgetListener *widgetListener)
virtual void drawBorder (Graphics *graphics)
virtual void drawOutline (Graphics *graphics)
virtual void drawSelectionFrame (Graphics *graphics)
void expandContent ()
virtual void expandContent (bool recursion)
virtual void focusNext ()
virtual void focusPrevious ()
virtual void getAbsolutePosition (int &x, int &y) const
std::string const & getActionEventId () const
Color const & getBackgroundColor () const
Color const & getBaseColor () const
Color const & getBorderColor () const
unsigned int getBorderSize () const
virtual Rectangle getChildrenArea ()
unsigned int getChildrenCount () const
Rectangle const & getDimension () const
Size const & getFixedSize () const
Font * getFont () const
Color const & getForegroundColor () const
int getHeight () const
std::string const & getId () const
void getLastPosition (int &x, int &y) const
int getMarginBottom () const
int getMarginLeft () const
int getMarginRight () const
int getMarginTop () const
Size const & getMaxSize () const
Size const & getMinSize () const
Color const & getOutlineColor () const
unsigned int getOutlineSize () const
unsigned int getPaddingBottom () const
unsigned int getPaddingLeft () const
unsigned int getPaddingRight () const
unsigned int getPaddingTop () const
virtual Widget * getParent () const
Color const & getSelectionColor () const
SelectionMode getSelectionMode () const
virtual Widget * getTop () const
unsigned int getVisibleChildrenCount () const
Widget * getWidgetAt (int x, int y)
virtual Widget * getWidgetAt (int x, int y, Widget *exclude)
std::list< Widget * > getWidgetsIn (Rectangle const &area)
virtual std::list< Widget * > getWidgetsIn (Rectangle const &area, Widget *ignore)
int getWidth () const
int getX () const
int getY () const
bool isEnabled () const
bool isFixedSize () const
bool isFocusable () const
virtual bool isFocused () const
bool isHorizontalExpand () const
bool isLastPositionSet () const
virtual bool isLayouted ()
virtual bool isModalFocusable () const
virtual bool isModalFocused () const
virtual bool isModalMouseInputFocusable () const
virtual bool isModalMouseInputFocused () const
bool isSetVisible () const
bool isTabInEnabled () const
bool isTabOutEnabled () const
bool isVerticalExpand () const
bool isVisible () const
virtual void logic ()
virtual void moveToBottom (Widget *widget)
virtual void moveToTop (Widget *widget)
Widget & operator= (Widget &&)=delete
Widget & operator= (Widget const &)=delete
virtual void releaseModalFocus ()
virtual void releaseModalMouseInputFocus ()
void removeActionListener (ActionListener *actionListener)
void removeDeathListener (DeathListener *deathListener)
void removeFocusListener (FocusListener *focusListener)
void removeKeyListener (KeyListener *keyListener)
void removeMouseListener (MouseListener *mouseListener)
void removeWidgetListener (WidgetListener *widgetListener)
virtual void requestFocus ()
virtual void requestModalFocus ()
virtual void requestModalMouseInputFocus ()
virtual void requestMoveToBottom ()
virtual void requestMoveToTop ()
void resizeToContent ()
void setActionEventId (std::string const &actionEventId)
virtual void setBackgroundColor (Color const &color)
virtual void setBaseColor (Color const &color)
virtual void setBorderColor (Color const &color)
void setBorderSize (unsigned int size)
void setDimension (Rectangle const &dimension)
void setEnabled (bool enabled)
void setFixedSize (Size const &size)
void setFocusable (bool focusable)
virtual void setFont (Font *font)
virtual void setForegroundColor (Color const &color)
void setHeight (int height)
void setHorizontalExpand (bool expand)
void setId (std::string const &id)
void setInternalFocusHandler (FocusHandler *internalFocusHandler)
void setLastPosition (int x, int y)
void setMargin (int margin)
void setMarginBottom (int margin)
void setMarginLeft (int margin)
void setMarginRight (int margin)
void setMarginTop (int margin)
void setMaxSize (Size const &size)
void setMinSize (Size const &size)
virtual void setOutlineColor (Color const &color)
void setOutlineSize (unsigned int size)
void setPadding (unsigned int padding)
void setPaddingBottom (unsigned int padding)
void setPaddingLeft (unsigned int padding)
void setPaddingRight (unsigned int padding)
void setPaddingTop (unsigned int padding)
void setPosition (int x, int y)
virtual void setSelectionColor (Color const &color)
virtual void setSelectionMode (SelectionMode mode)
void setSize (int width, int height)
void setTabInEnabled (bool enabled)
void setTabOutEnabled (bool enabled)
void setVerticalExpand (bool expand)
void setVisible (bool visible)
void setWidth (int width)
void setX (int x)
void setY (int y)
virtual void showPart (Rectangle rectangle)
virtual void showWidgetPart (Widget *widget, Rectangle area)
Widget ()
Widget (Widget &&)=delete
Widget (Widget const &)=delete
Public Member Functions inherited from fcn::MouseListener
virtual void mouseClicked (MouseEvent &mouseEvent)
MouseListener (MouseListener &&)=default
MouseListener (MouseListener const &)=default
virtual void mouseMoved (MouseEvent &mouseEvent)
virtual void mouseWheelMovedDown (MouseEvent &mouseEvent)
virtual void mouseWheelMovedLeft (MouseEvent &mouseEvent)
virtual void mouseWheelMovedRight (MouseEvent &mouseEvent)
virtual void mouseWheelMovedUp (MouseEvent &mouseEvent)
MouseListener & operator= (MouseListener &&)=default
MouseListener & operator= (MouseListener const &)=default
Public Member Functions inherited from fcn::KeyListener
KeyListener (KeyListener &&)=default
KeyListener (KeyListener const &)=default
KeyListener & operator= (KeyListener &&)=default
KeyListener & operator= (KeyListener const &)=default
Public Member Functions inherited from fcn::FocusListener
virtual void focusGained (Event const &event)
FocusListener (FocusListener &&)=delete
FocusListener (FocusListener const &)=delete
FocusListener & operator= (FocusListener &&)=delete
FocusListener & operator= (FocusListener const &)=delete
Public Member Functions inherited from fcn::WidgetListener
virtual void ancestorMoved (Event const &event)
virtual void ancestorShown (Event const &event)
WidgetListener & operator= (WidgetListener &&)=default
WidgetListener & operator= (WidgetListener const &)=default
virtual void widgetHidden (Event const &event)
WidgetListener (WidgetListener &&)=default
WidgetListener (WidgetListener const &)=default
virtual void widgetMoved (Event const &event)
virtual void widgetResized (Event const &event)
virtual void widgetShown (Event const &event)
Protected Member Functions
virtual void adjustSizeImpl ()
virtual bool isPressed () const
Protected Member Functions inherited from fcn::Widget
void add (Widget *widget)
void calculateSize ()
void distributeActionEvent ()
void distributeAncestorHiddenEvent (Widget *ancestor)
void distributeAncestorMovedEvent (Widget *ancestor)
void distributeAncestorShownEvent (Widget *ancestor)
void distributeHiddenEvent ()
void distributeMovedEvent ()
void distributeResizedEvent ()
void distributeShownEvent ()
virtual Widget * findWidgetById (std::string const &id)
std::list< Widget * > const & getChildren () const
virtual void remove (Widget *widget)
virtual void removeAllChildren ()
void resizeToChildren ()
Protected Member Functions inherited from fcn::MouseListener
MouseListener ()=default
Protected Member Functions inherited from fcn::KeyListener
KeyListener ()=default
Protected Member Functions inherited from fcn::FocusListener
FocusListener ()=default
Protected Member Functions inherited from fcn::WidgetListener
WidgetListener ()=default
Protected Attributes
Graphics::Alignment mAlignment {Graphics::Alignment::Center}
std::string mCaption
bool mHasMouse {false}
bool mKeyPressed {false}
bool mMousePressed {false}
bool mState {true}
int mXOffset {1}
int mYOffset {1}
Protected Attributes inherited from fcn::Widget
std::string mActionEventId
std::list< ActionListener * > mActionListeners
Color mBackgroundColor {0xf9fafb}
Color mBaseColor {0xe5e7eb}
Color mBorderColor {0xd1d5db}
unsigned int mBorderSize {0}
std::list< Widget * > mChildren
Font * mCurrentFont {nullptr}
std::list< DeathListener * > mDeathListeners
Rectangle mDimension
bool mEnabled {true}
Size mFixedSize {-1, -1}
bool mFixedSizeUsed {false}
bool mFocusable {false}
FocusHandler * mFocusHandler {nullptr}
std::list< FocusListener * > mFocusListeners
Color mForegroundColor {0x1f2933}
bool mHExpand {false}
std::string mId
FocusHandler * mInternalFocusHandler {nullptr}
std::list< KeyListener * > mKeyListeners
int mLastX {0}
int mLastY {0}
int mMarginBottom {0}
int mMarginLeft {0}
int mMarginRight {0}
int mMarginTop {0}
Size mMaxSize {std::numeric_limits<int>::max(), std::numeric_limits<int>::max()}
Size mMinSize {0, 0}
std::list< MouseListener * > mMouseListeners
Rectangle mOffsetRect
Color mOutlineColor {0x9ca3af}
unsigned int mOutlineSize {0}
unsigned int mPaddingBottom {0}
unsigned int mPaddingLeft {0}
unsigned int mPaddingRight {0}
unsigned int mPaddingTop {0}
Widget * mParent {nullptr}
Color mSelectionColor {0x3b82f6}
SelectionMode mSelectionMode {SelectionMode::None}
bool mTabIn {true}
bool mTabOut {true}
bool mVExpand {false}
bool mVisible {true}
std::list< WidgetListener * > mWidgetListeners
Additional Inherited Members
Public Types inherited from fcn::Widget
enum class SelectionMode : uint8_t { None = 0 , Border = 1 , Background = 2 }
Static Public Member Functions inherited from fcn::Widget
static DeathListener * _getGuiDeathListener ()
static VisibilityEventHandler * _getVisibilityEventHandler ()
static void _setGuiDeathListener (DeathListener *deathListener)
static void _setVisibilityEventHandler (VisibilityEventHandler *visibilityEventHandler)
static void setGlobalFont (Font *font)
static bool widgetExists (Widget const *widget)
Static Protected Attributes inherited from fcn::Widget
static DefaultFont mDefaultFont
static Font * mGlobalFont = nullptr
static DeathListener * mGuiDeathListener = nullptr
static VisibilityEventHandler * mVisibilityEventHandler = nullptr
static std::list< Widget * > mWidgetInstances
Detailed Description
A standard clickable button widget.
A button is capable of displaying a caption. If a button is clicked an action event will be sent to all action listener's of the button.
See also
ImageButton
Definition at line 32 of file button.hpp.
Constructor & Destructor Documentation
Button() [1/2]
fcn::Button::Button ()
Definition at line 19 of file button.cpp.
Button() [2/2]
fcn::Button::Button (std::string caption) explicit
Constructor.
The button will be automatically resized to fit the caption.
Parameters
caption The caption of the button.
Definition at line 30 of file button.cpp.
References fcn::Widget::addFocusListener(), fcn::Widget::addKeyListener(), fcn::Widget::addMouseListener(), fcn::Widget::addWidgetListener(), adjustSizeImpl(), mCaption, and fcn::Widget::setFocusable().
Member Function Documentation
adjustSize()
void fcn::Button::adjustSize () override virtual
Resizes the widget's size to fit the content exactly.
Reimplemented from fcn::Widget.
Reimplemented in fcn::CheckBox, and fcn::ImageButton.
Definition at line 173 of file button.cpp.
References adjustSizeImpl().
adjustSizeImpl()
void fcn::Button::adjustSizeImpl () protected virtual
Adjusts the size of the button to fit the caption.
The public adjustSize() method serves as a virtual entry point for polymorphism, while this adjustSizeImpl() method contains the concrete implementation of the resizing logic.
See also
adjustSize (virtual entry point for polymorphism)
Reimplemented in fcn::CheckBox, and fcn::ImageButton.
Definition at line 178 of file button.cpp.
References fcn::Widget::getBorderSize(), fcn::Widget::getFont(), fcn::Font::getHeight(), fcn::Widget::getPaddingBottom(), fcn::Widget::getPaddingLeft(), fcn::Widget::getPaddingRight(), fcn::Widget::getPaddingTop(), fcn::Font::getWidth(), mCaption, and fcn::Widget::setSize().
Referenced by adjustSize(), Button(), fontChanged(), resizeToContent(), and setCaption().
ancestorHidden()
void fcn::Button::ancestorHidden (Event const & event) override virtual
Invoked when an ancestor of a widget is hidden, i.e its set to be not visible.
Parameters
event Describes the event.
Reimplemented from fcn::WidgetListener.
Definition at line 256 of file button.cpp.
References mHasMouse, mKeyPressed, and mMousePressed.
draw()
void fcn::Button::draw (Graphics * graphics) override virtual
Draws the widget.
The call to draw is initiated by the widget's parent. The graphics object is set up so that all drawing is relative to the widget, i.e coordinate (0,0) is the top left corner of the widget. It is not possible to draw outside of a widget's dimension. If a widget has children, the parent's draw function will always be called before the children's draw functions are called.
NOTE: A widget with children won't draw its children unless the children area given by Widget::getChildrenArea returns a none empty rectangle inside the widgets dimension. The children area is considered relative to the widget's position.
Parameters
Graphics & Rendering A graphics object to draw with.
See also
getChildrenArea, drawOutline, drawBorder
Implements fcn::Widget.
Reimplemented in fcn::CheckBox, and fcn::ImageButton.
Definition at line 105 of file button.cpp.
References fcn::Color::a, fcn::Color::b, fcn::Widget::drawBorder(), fcn::Widget::drawSelectionFrame(), fcn::Graphics::drawText(), fcn::Graphics::fillRectangle(), fcn::Color::g, getAlignment(), fcn::Widget::getBaseColor(), fcn::Widget::getBorderSize(), getCaption(), getDownXOffset(), getDownYOffset(), fcn::Widget::getFont(), fcn::Widget::getForegroundColor(), fcn::Font::getHeight(), fcn::Widget::getHeight(), fcn::Widget::getPaddingBottom(), fcn::Widget::getPaddingLeft(), fcn::Widget::getPaddingRight(), fcn::Widget::getPaddingTop(), fcn::Widget::getSelectionColor(), fcn::Widget::getSelectionMode(), fcn::Widget::getWidth(), fcn::Rectangle::height, isActive(), fcn::Widget::isFocused(), isPressed(), fcn::Color::r, fcn::Graphics::setColor(), fcn::Graphics::setFont(), fcn::Rectangle::width, fcn::Rectangle::x, and fcn::Rectangle::y.
focusLost()
void fcn::Button::focusLost (Event const & event) override virtual
Called when a widget loses focus.
Parameters
event Describes the event.
Reimplemented from fcn::FocusListener.
Definition at line 249 of file button.cpp.
References mHasMouse, mKeyPressed, and mMousePressed.
fontChanged()
void fcn::Button::fontChanged () override virtual
Called when the font has changed.
If the change is global, this function will only be called if the widget doesn't have a font already set.
Reimplemented from fcn::Widget.
Definition at line 100 of file button.cpp.
References adjustSizeImpl().
getAlignment()
Graphics::Alignment fcn::Button::getAlignment () const
Gets the alignment of the caption.
Returns
The alignment of the caption.
See also
setAlignment, Graphics
Definition at line 69 of file button.cpp.
References mAlignment.
Referenced by draw(), and fcn::ImageButton::draw().
getCaption()
std::string const & fcn::Button::getCaption () const
Gets the caption of the button.
Returns
The caption of the button.
Definition at line 49 of file button.cpp.
References mCaption.
Referenced by fcn::CheckBox::adjustSizeImpl(), fcn::ImageButton::adjustSizeImpl(), draw(), fcn::CheckBox::draw(), and fcn::ImageButton::draw().
getDownXOffset()
int fcn::Button::getDownXOffset () const
Gets the number of pixels the image or text will be offset.
Returns
The x offset.
Definition at line 79 of file button.cpp.
References mXOffset.
Referenced by draw(), fcn::ImageButton::draw(), and fcn::CheckBox::drawMarkerImage().
getDownYOffset()
int fcn::Button::getDownYOffset () const
Gets the number of pixels the image or text will be offset.
Returns
The y offset.
Definition at line 89 of file button.cpp.
References mYOffset.
Referenced by draw(), fcn::ImageButton::draw(), and fcn::CheckBox::drawMarkerImage().
isActive()
bool fcn::Button::isActive () const
Returns the button state.
Returns
True if the button is active otherwise false.
Definition at line 59 of file button.cpp.
References mState.
Referenced by draw(), fcn::ImageButton::draw(), and fcn::CheckBox::drawMarkerImage().
isPressed()
bool fcn::Button::isPressed () const protected virtual
Checks if the button is pressed.
Convenient method to use when overloading the draw method of the button.
Returns
True if the button is pressed, false otherwise.
Reimplemented in fcn::ToggleButton.
Definition at line 185 of file button.cpp.
References mHasMouse, mKeyPressed, and mMousePressed.
Referenced by draw(), and fcn::ImageButton::draw().
keyPressed()
void fcn::Button::keyPressed (KeyEvent & keyEvent) override virtual
Called if a key is pressed when the widget has keyboard focus.
If a key is held down the widget will generate multiple key presses.
Parameters
keyEvent Describes the event.
Reimplemented from fcn::KeyListener.
Reimplemented in fcn::CheckBox.
Definition at line 228 of file button.cpp.
References fcn::InputEvent::consume(), fcn::KeyEvent::getKey(), fcn::Key::getValue(), and mKeyPressed.
keyReleased()
void fcn::Button::keyReleased (KeyEvent & keyEvent) override virtual
Called if a key is released when the widget has keyboard focus.
Parameters
keyEvent Describes the event.
Reimplemented from fcn::KeyListener.
Reimplemented in fcn::CheckBox, and fcn::ToggleButton.
Definition at line 238 of file button.cpp.
References fcn::InputEvent::consume(), fcn::Widget::distributeActionEvent(), fcn::KeyEvent::getKey(), fcn::Key::getValue(), and mKeyPressed.
mouseDragged()
void fcn::Button::mouseDragged (MouseEvent & mouseEvent) override virtual
Called when the mouse has moved and the mouse has previously been pressed on the widget.
Parameters
mouseEvent Describes the event.
Reimplemented from fcn::MouseListener.
Definition at line 223 of file button.cpp.
References fcn::InputEvent::consume().
mouseEntered()
void fcn::Button::mouseEntered (MouseEvent & mouseEvent) override virtual
Called when the mouse has entered into the widget area.
Parameters
mouseEvent Describes the event.
Reimplemented from fcn::MouseListener.
Definition at line 206 of file button.cpp.
References mHasMouse.
mouseExited()
void fcn::Button::mouseExited (MouseEvent & mouseEvent) override virtual
Called when the mouse has exited the widget area.
Parameters
mouseEvent Describes the event.
Reimplemented from fcn::MouseListener.
Definition at line 201 of file button.cpp.
References mHasMouse.
mousePressed()
void fcn::Button::mousePressed (MouseEvent & mouseEvent) override virtual
Called when a mouse button has been pressed on the widget area.
NOTE: A mouse press is NOT equal to a mouse click. Use mouseClickMessage to check for mouse clicks.
Parameters
mouseEvent Describes the event.
Reimplemented from fcn::MouseListener.
Reimplemented in fcn::CheckBox.
Definition at line 193 of file button.cpp.
References fcn::InputEvent::consume(), fcn::MouseEvent::getButton(), and mMousePressed.
mouseReleased()
void fcn::Button::mouseReleased (MouseEvent & mouseEvent) override virtual
Called when a mouse button has been released on the widget area.
Parameters
mouseEvent Describes the event.
Reimplemented from fcn::MouseListener.
Reimplemented in fcn::CheckBox, and fcn::ToggleButton.
Definition at line 211 of file button.cpp.
References fcn::InputEvent::consume(), fcn::Widget::distributeActionEvent(), fcn::MouseEvent::getButton(), mHasMouse, and mMousePressed.
resizeToContent() [1/2]
void fcn::Widget::resizeToContent () inline
Resizes the widget's size to fit the content exactly, calls recursively all childs.
This is a convenience wrapper that calls resizeToContent(true).
Definition at line 1417 of file widget.hpp.
resizeToContent() [2/2]
void fcn::Button::resizeToContent (bool recursion) override virtual
Resize this widget to fit its content.
Parameters
recursion If true, perform the resize operation recursively on children.
Reimplemented from fcn::Widget.
Reimplemented in fcn::ImageButton.
Definition at line 167 of file button.cpp.
References adjustSizeImpl().
setActive()
void fcn::Button::setActive (bool state)
Sets the button state.
If the button is inactive it looks gray.
Parameters
state True to activate the button or false to deactivate it.
Definition at line 54 of file button.cpp.
References mState.
setAlignment()
void fcn::Button::setAlignment (Graphics::Alignment alignment)
Sets the alignment of the caption.
The alignment is relative to the center of the button.
Parameters
alignment The alignment of the caption.
See also
getAlignment, Graphics
Definition at line 64 of file button.cpp.
References mAlignment.
setCaption()
void fcn::Button::setCaption (std::string const & caption)
Sets the caption of the button.
Parameters
caption The caption of the button.
See also
getCaption, adjustSize
Definition at line 43 of file button.cpp.
References adjustSizeImpl(), and mCaption.
Referenced by fcn::CheckBox::CheckBox(), fcn::RadioButton::RadioButton(), and fcn::ToggleButton::ToggleButton().
setDownOffset()
void fcn::Button::setDownOffset (int x, int y)
Sets the number of pixels the image or text will be offset from the top left corner of button when the button is pressed or toggled.
Parameters
x The x offset.
y The y offset.
Definition at line 94 of file button.cpp.
References mXOffset, and mYOffset.
setDownXOffset()
void fcn::Button::setDownXOffset (int offset)
Sets the number of pixels the image or text will be offset from the top left corner of button when the button is pressed or toggled.
Parameters
offset The x offset.
Definition at line 74 of file button.cpp.
References mXOffset.
setDownYOffset()
void fcn::Button::setDownYOffset (int offset)
Sets the number of pixels the image or text will be offset from the top left corner of button when the button is pressed or toggled.
Parameters
offset The y offset.
Definition at line 84 of file button.cpp.
References mYOffset.
Member Data Documentation
mAlignment
Graphics::Alignment fcn::Button::mAlignment {Graphics::Alignment::Center} protected
Holds the alignment of the caption.
Definition at line 221 of file button.hpp.
Referenced by getAlignment(), and setAlignment().
mCaption
std::string fcn::Button::mCaption protected
Holds the caption of the button.
Definition at line 196 of file button.hpp.
Referenced by adjustSizeImpl(), Button(), getCaption(), and setCaption().
mHasMouse
bool fcn::Button::mHasMouse {false} protected
True if the mouse is on top of the button, false otherwise.
Definition at line 201 of file button.hpp.
Referenced by ancestorHidden(), fcn::ImageButton::draw(), fcn::CheckBox::drawMarkerImage(), focusLost(), isPressed(), fcn::CheckBox::mouseClicked(), mouseEntered(), mouseExited(), fcn::CheckBox::mousePressed(), mouseReleased(), fcn::CheckBox::mouseReleased(), and fcn::ToggleButton::mouseReleased().
mKeyPressed
bool fcn::Button::mKeyPressed {false} protected
True if a key has been pressed, false otherwise.
Definition at line 206 of file button.hpp.
Referenced by ancestorHidden(), focusLost(), isPressed(), keyPressed(), keyReleased(), and fcn::ToggleButton::keyReleased().
mMousePressed
bool fcn::Button::mMousePressed {false} protected
True if a mouse has been pressed, false otherwise.
Definition at line 211 of file button.hpp.
Referenced by ancestorHidden(), focusLost(), isPressed(), mousePressed(), mouseReleased(), and fcn::ToggleButton::mouseReleased().
mState
bool fcn::Button::mState {true} protected
True if the button is active.
Definition at line 216 of file button.hpp.
Referenced by isActive(), and setActive().
mXOffset
int fcn::Button::mXOffset {1} protected
Holds the x down offset of the caption.
Definition at line 226 of file button.hpp.
Referenced by getDownXOffset(), setDownOffset(), and setDownXOffset().
mYOffset
int fcn::Button::mYOffset {1} protected
Holds the y down offset of the caption.
Definition at line 231 of file button.hpp.
Referenced by getDownYOffset(), setDownOffset(), and setDownYOffset().
The documentation for this class was generated from the following files:
button.hpp
button.cpp