FifeGUI: fcn::PointGraph Class Reference
fcn::PointGraph Class Reference
Graph Widgets
#include <pointgraph.hpp>
Public Member Functions
void draw (Graphics *graphics) override
PointVector const & getPointVector () const
unsigned int getThickness () const
bool isOpaque () const
PointGraph & operator= (PointGraph &&)=delete
PointGraph & operator= (PointGraph const &)=delete
PointGraph ()
PointGraph (PointGraph &&)=delete
PointGraph (PointGraph const &)=delete
PointGraph (PointVector data)
void resetPointVector ()
void setOpaque (bool opaque)
void setPointVector (PointVector const &data)
void setThickness (unsigned int thickness)
Public Member Functions inherited from fcn::Widget
virtual void _draw (Graphics *graphics)
virtual FocusHandler * _getFocusHandler ()
virtual std::list< FocusListener * > const & _getFocusListeners ()
virtual FocusHandler * _getInternalFocusHandler ()
virtual std::list< KeyListener * > const & _getKeyListeners ()
virtual std::list< MouseListener * > const & _getMouseListeners ()
virtual void _logic ()
virtual void _setFocusHandler (FocusHandler *focusHandler)
virtual void _setParent (Widget *parent)
void adaptLayout ()
virtual void adaptLayout (bool top)
void addActionListener (ActionListener *actionListener)
void addDeathListener (DeathListener *deathListener)
void addFocusListener (FocusListener *focusListener)
void addKeyListener (KeyListener *keyListener)
void addMouseListener (MouseListener *mouseListener)
void addWidgetListener (WidgetListener *widgetListener)
virtual void adjustSize ()
virtual void drawBorder (Graphics *graphics)
virtual void drawOutline (Graphics *graphics)
virtual void drawSelectionFrame (Graphics *graphics)
void expandContent ()
virtual void expandContent (bool recursion)
virtual void focusNext ()
virtual void focusPrevious ()
virtual void fontChanged ()
virtual void getAbsolutePosition (int &x, int &y) const
std::string const & getActionEventId () const
Color const & getBackgroundColor () const
Color const & getBaseColor () const
Color const & getBorderColor () const
unsigned int getBorderSize () const
virtual Rectangle getChildrenArea ()
unsigned int getChildrenCount () const
Rectangle const & getDimension () const
Size const & getFixedSize () const
Font * getFont () const
Color const & getForegroundColor () const
int getHeight () const
std::string const & getId () const
void getLastPosition (int &x, int &y) const
int getMarginBottom () const
int getMarginLeft () const
int getMarginRight () const
int getMarginTop () const
Size const & getMaxSize () const
Size const & getMinSize () const
Color const & getOutlineColor () const
unsigned int getOutlineSize () const
unsigned int getPaddingBottom () const
unsigned int getPaddingLeft () const
unsigned int getPaddingRight () const
unsigned int getPaddingTop () const
virtual Widget * getParent () const
Color const & getSelectionColor () const
SelectionMode getSelectionMode () const
virtual Widget * getTop () const
unsigned int getVisibleChildrenCount () const
Widget * getWidgetAt (int x, int y)
virtual Widget * getWidgetAt (int x, int y, Widget *exclude)
std::list< Widget * > getWidgetsIn (Rectangle const &area)
virtual std::list< Widget * > getWidgetsIn (Rectangle const &area, Widget *ignore)
int getWidth () const
int getX () const
int getY () const
bool isEnabled () const
bool isFixedSize () const
bool isFocusable () const
virtual bool isFocused () const
bool isHorizontalExpand () const
bool isLastPositionSet () const
virtual bool isLayouted ()
virtual bool isModalFocusable () const
virtual bool isModalFocused () const
virtual bool isModalMouseInputFocusable () const
virtual bool isModalMouseInputFocused () const
bool isSetVisible () const
bool isTabInEnabled () const
bool isTabOutEnabled () const
bool isVerticalExpand () const
bool isVisible () const
virtual void logic ()
virtual void moveToBottom (Widget *widget)
virtual void moveToTop (Widget *widget)
Widget & operator= (Widget &&)=delete
Widget & operator= (Widget const &)=delete
virtual void releaseModalFocus ()
virtual void releaseModalMouseInputFocus ()
void removeActionListener (ActionListener *actionListener)
void removeDeathListener (DeathListener *deathListener)
void removeFocusListener (FocusListener *focusListener)
void removeKeyListener (KeyListener *keyListener)
void removeMouseListener (MouseListener *mouseListener)
void removeWidgetListener (WidgetListener *widgetListener)
virtual void requestFocus ()
virtual void requestModalFocus ()
virtual void requestModalMouseInputFocus ()
virtual void requestMoveToBottom ()
virtual void requestMoveToTop ()
void resizeToContent ()
virtual void resizeToContent (bool recursion)
void setActionEventId (std::string const &actionEventId)
virtual void setBackgroundColor (Color const &color)
virtual void setBaseColor (Color const &color)
virtual void setBorderColor (Color const &color)
void setBorderSize (unsigned int size)
void setDimension (Rectangle const &dimension)
void setEnabled (bool enabled)
void setFixedSize (Size const &size)
void setFocusable (bool focusable)
virtual void setFont (Font *font)
virtual void setForegroundColor (Color const &color)
void setHeight (int height)
void setHorizontalExpand (bool expand)
void setId (std::string const &id)
void setInternalFocusHandler (FocusHandler *internalFocusHandler)
void setLastPosition (int x, int y)
void setMargin (int margin)
void setMarginBottom (int margin)
void setMarginLeft (int margin)
void setMarginRight (int margin)
void setMarginTop (int margin)
void setMaxSize (Size const &size)
void setMinSize (Size const &size)
virtual void setOutlineColor (Color const &color)
void setOutlineSize (unsigned int size)
void setPadding (unsigned int padding)
void setPaddingBottom (unsigned int padding)
void setPaddingLeft (unsigned int padding)
void setPaddingRight (unsigned int padding)
void setPaddingTop (unsigned int padding)
void setPosition (int x, int y)
virtual void setSelectionColor (Color const &color)
virtual void setSelectionMode (SelectionMode mode)
void setSize (int width, int height)
void setTabInEnabled (bool enabled)
void setTabOutEnabled (bool enabled)
void setVerticalExpand (bool expand)
void setVisible (bool visible)
void setWidth (int width)
void setX (int x)
void setY (int y)
virtual void showPart (Rectangle rectangle)
virtual void showWidgetPart (Widget *widget, Rectangle area)
Widget ()
Widget (Widget &&)=delete
Widget (Widget const &)=delete
Protected Attributes
PointVector m_data
bool m_opaque
unsigned int m_thickness
Protected Attributes inherited from fcn::Widget
std::string mActionEventId
std::list< ActionListener * > mActionListeners
Color mBackgroundColor {0xf9fafb}
Color mBaseColor {0xe5e7eb}
Color mBorderColor {0xd1d5db}
unsigned int mBorderSize {0}
std::list< Widget * > mChildren
Font * mCurrentFont {nullptr}
std::list< DeathListener * > mDeathListeners
Rectangle mDimension
bool mEnabled {true}
Size mFixedSize {-1, -1}
bool mFixedSizeUsed {false}
bool mFocusable {false}
FocusHandler * mFocusHandler {nullptr}
std::list< FocusListener * > mFocusListeners
Color mForegroundColor {0x1f2933}
bool mHExpand {false}
std::string mId
FocusHandler * mInternalFocusHandler {nullptr}
std::list< KeyListener * > mKeyListeners
int mLastX {0}
int mLastY {0}
int mMarginBottom {0}
int mMarginLeft {0}
int mMarginRight {0}
int mMarginTop {0}
Size mMaxSize {std::numeric_limits<int>::max(), std::numeric_limits<int>::max()}
Size mMinSize {0, 0}
std::list< MouseListener * > mMouseListeners
Rectangle mOffsetRect
Color mOutlineColor {0x9ca3af}
unsigned int mOutlineSize {0}
unsigned int mPaddingBottom {0}
unsigned int mPaddingLeft {0}
unsigned int mPaddingRight {0}
unsigned int mPaddingTop {0}
Widget * mParent {nullptr}
Color mSelectionColor {0x3b82f6}
SelectionMode mSelectionMode {SelectionMode::None}
bool mTabIn {true}
bool mTabOut {true}
bool mVExpand {false}
bool mVisible {true}
std::list< WidgetListener * > mWidgetListeners
Additional Inherited Members
Public Types inherited from fcn::Widget
enum class SelectionMode : uint8_t { None = 0 , Border = 1 , Background = 2 }
Static Public Member Functions inherited from fcn::Widget
static DeathListener * _getGuiDeathListener ()
static VisibilityEventHandler * _getVisibilityEventHandler ()
static void _setGuiDeathListener (DeathListener *deathListener)
static void _setVisibilityEventHandler (VisibilityEventHandler *visibilityEventHandler)
static void setGlobalFont (Font *font)
static bool widgetExists (Widget const *widget)
Protected Member Functions inherited from fcn::Widget
void add (Widget *widget)
void calculateSize ()
void distributeActionEvent ()
void distributeAncestorHiddenEvent (Widget *ancestor)
void distributeAncestorMovedEvent (Widget *ancestor)
void distributeAncestorShownEvent (Widget *ancestor)
void distributeHiddenEvent ()
void distributeMovedEvent ()
void distributeResizedEvent ()
void distributeShownEvent ()
virtual Widget * findWidgetById (std::string const &id)
std::list< Widget * > const & getChildren () const
virtual void remove (Widget *widget)
virtual void removeAllChildren ()
void resizeToChildren ()
Static Protected Attributes inherited from fcn::Widget
static DefaultFont mDefaultFont
static Font * mGlobalFont = nullptr
static DeathListener * mGuiDeathListener = nullptr
static VisibilityEventHandler * mVisibilityEventHandler = nullptr
static std::list< Widget * > mWidgetInstances
Detailed Description
Draws a scatter graph of individual points.
The graph is drawn by connecting the points with lines. The thickness of the lines can be set with setThickness. The graph can be set to be opaque or not with setOpaque. If the graph is opaque, it will be drawn with a solid color, otherwise it will be drawn with a transparent color.
Definition at line 26 of file pointgraph.hpp.
Constructor & Destructor Documentation
PointGraph() [1/2]
fcn::PointGraph::PointGraph ()
Default constructor.
Definition at line 16 of file pointgraph.cpp.
References m_opaque, and m_thickness.
PointGraph() [2/2]
fcn::PointGraph::PointGraph (PointVector data) explicit
Construct with initial data points.
Parameters
data Initial data points to show in the graph.
Definition at line 18 of file pointgraph.cpp.
References m_data, m_opaque, and m_thickness.
Member Function Documentation
draw()
void fcn::PointGraph::draw (Graphics * graphics) override virtual
Draws this widget.
Implements fcn::Widget.
Definition at line 55 of file pointgraph.cpp.
References fcn::Widget::drawBorder(), fcn::Graphics::drawFillCircle(), fcn::Graphics::drawLine(), fcn::Graphics::drawRoundStroke(), fcn::Widget::drawSelectionFrame(), fcn::Graphics::fillRectangle(), fcn::Widget::getBackgroundColor(), fcn::Widget::getBaseColor(), fcn::Widget::getBorderSize(), fcn::Widget::getHeight(), fcn::Widget::getSelectionColor(), fcn::Widget::getSelectionMode(), fcn::Widget::getWidth(), fcn::Widget::isFocused(), isOpaque(), m_data, m_thickness, and fcn::Graphics::setColor().
getPointVector()
PointVector const & fcn::PointGraph::getPointVector () const
Returns
The data to draw.
Definition at line 25 of file pointgraph.cpp.
References m_data.
getThickness()
unsigned int fcn::PointGraph::getThickness () const
Get the thickness of the lines drawn between points.
Returns
Line thickness in pixels.
Definition at line 40 of file pointgraph.cpp.
References m_thickness.
isOpaque()
bool fcn::PointGraph::isOpaque () const
Returns
Whether this graph is opaque or not.
Definition at line 50 of file pointgraph.cpp.
References m_opaque.
Referenced by draw().
resetPointVector()
void fcn::PointGraph::resetPointVector ()
Resets the data to draw.
Definition at line 30 of file pointgraph.cpp.
References m_data.
setOpaque()
void fcn::PointGraph::setOpaque (bool opaque)
Sets the opacity of the graph.
Parameters
opaque True if opaque, false otherwise.
Definition at line 45 of file pointgraph.cpp.
References m_opaque.
setPointVector()
void fcn::PointGraph::setPointVector (PointVector const & data)
Sets the data to draw.
Parameters
data The data to draw.
Definition at line 20 of file pointgraph.cpp.
References m_data.
setThickness()
void fcn::PointGraph::setThickness (unsigned int thickness)
Set the thickness of the lines drawn between points.
Parameters
thickness Line thickness in pixels.
Definition at line 35 of file pointgraph.cpp.
References m_thickness.
Member Data Documentation
m_data
PointVector fcn::PointGraph::m_data protected
The point data used to draw the graph.
Definition at line 102 of file pointgraph.hpp.
Referenced by draw(), getPointVector(), PointGraph(), resetPointVector(), and setPointVector().
m_opaque
bool fcn::PointGraph::m_opaque protected
True if the graph is drawn opaque.
Definition at line 96 of file pointgraph.hpp.
Referenced by isOpaque(), PointGraph(), PointGraph(), and setOpaque().
m_thickness
unsigned int fcn::PointGraph::m_thickness protected
Line thickness in pixels.
Definition at line 99 of file pointgraph.hpp.
Referenced by draw(), getThickness(), PointGraph(), PointGraph(), and setThickness().
The documentation for this class was generated from the following files:
pointgraph.hpp
pointgraph.cpp