FifeGUI: fcn::ImageProgressBar Class Reference
fcn::ImageProgressBar Class Reference
Graph Widgets
#include <imageprogressbar.hpp>
Public Types
enum class Orientation : uint8_t { Horizontal = 0 , Vertical }
Public Types inherited from fcn::Widget
enum class SelectionMode : uint8_t { None = 0 , Border = 1 , Background = 2 }
Public Member Functions
void adjustSize () override
void draw (Graphics *graphics) override
Image const * getBarImage () const
Image const * getForegroundImage () const
int getMaxValue () const
Orientation getOrientation () const
int getValue () const
ImageProgressBar (Image *image, int maxValue)
ImageProgressBar (ImageProgressBar &&)=delete
ImageProgressBar (ImageProgressBar const &)=delete
ImageProgressBar (std::string const &filename, int maxValue)
bool isOpaque () const
ImageProgressBar & operator= (ImageProgressBar &&)=delete
ImageProgressBar & operator= (ImageProgressBar const &)=delete
void resizeToContent ()
void resizeToContent (bool recursion) override
void setBarImage (Image *image)
void setForegroundImage (Image *image)
void setMaxValue (int value)
void setOpaque (bool opaque)
void setOrientation (Orientation orientation)
void setValue (int value)
Public Member Functions inherited from fcn::Widget
virtual void _draw (Graphics *graphics)
virtual FocusHandler * _getFocusHandler ()
virtual std::list< FocusListener * > const & _getFocusListeners ()
virtual FocusHandler * _getInternalFocusHandler ()
virtual std::list< KeyListener * > const & _getKeyListeners ()
virtual std::list< MouseListener * > const & _getMouseListeners ()
virtual void _logic ()
virtual void _setFocusHandler (FocusHandler *focusHandler)
virtual void _setParent (Widget *parent)
void adaptLayout ()
virtual void adaptLayout (bool top)
void addActionListener (ActionListener *actionListener)
void addDeathListener (DeathListener *deathListener)
void addFocusListener (FocusListener *focusListener)
void addKeyListener (KeyListener *keyListener)
void addMouseListener (MouseListener *mouseListener)
void addWidgetListener (WidgetListener *widgetListener)
virtual void drawBorder (Graphics *graphics)
virtual void drawOutline (Graphics *graphics)
virtual void drawSelectionFrame (Graphics *graphics)
void expandContent ()
virtual void expandContent (bool recursion)
virtual void focusNext ()
virtual void focusPrevious ()
virtual void fontChanged ()
virtual void getAbsolutePosition (int &x, int &y) const
std::string const & getActionEventId () const
Color const & getBackgroundColor () const
Color const & getBaseColor () const
Color const & getBorderColor () const
unsigned int getBorderSize () const
virtual Rectangle getChildrenArea ()
unsigned int getChildrenCount () const
Rectangle const & getDimension () const
Size const & getFixedSize () const
Font * getFont () const
Color const & getForegroundColor () const
int getHeight () const
std::string const & getId () const
void getLastPosition (int &x, int &y) const
int getMarginBottom () const
int getMarginLeft () const
int getMarginRight () const
int getMarginTop () const
Size const & getMaxSize () const
Size const & getMinSize () const
Color const & getOutlineColor () const
unsigned int getOutlineSize () const
unsigned int getPaddingBottom () const
unsigned int getPaddingLeft () const
unsigned int getPaddingRight () const
unsigned int getPaddingTop () const
virtual Widget * getParent () const
Color const & getSelectionColor () const
SelectionMode getSelectionMode () const
virtual Widget * getTop () const
unsigned int getVisibleChildrenCount () const
Widget * getWidgetAt (int x, int y)
virtual Widget * getWidgetAt (int x, int y, Widget *exclude)
std::list< Widget * > getWidgetsIn (Rectangle const &area)
virtual std::list< Widget * > getWidgetsIn (Rectangle const &area, Widget *ignore)
int getWidth () const
int getX () const
int getY () const
bool isEnabled () const
bool isFixedSize () const
bool isFocusable () const
virtual bool isFocused () const
bool isHorizontalExpand () const
bool isLastPositionSet () const
virtual bool isLayouted ()
virtual bool isModalFocusable () const
virtual bool isModalFocused () const
virtual bool isModalMouseInputFocusable () const
virtual bool isModalMouseInputFocused () const
bool isSetVisible () const
bool isTabInEnabled () const
bool isTabOutEnabled () const
bool isVerticalExpand () const
bool isVisible () const
virtual void logic ()
virtual void moveToBottom (Widget *widget)
virtual void moveToTop (Widget *widget)
Widget & operator= (Widget &&)=delete
Widget & operator= (Widget const &)=delete
virtual void releaseModalFocus ()
virtual void releaseModalMouseInputFocus ()
void removeActionListener (ActionListener *actionListener)
void removeDeathListener (DeathListener *deathListener)
void removeFocusListener (FocusListener *focusListener)
void removeKeyListener (KeyListener *keyListener)
void removeMouseListener (MouseListener *mouseListener)
void removeWidgetListener (WidgetListener *widgetListener)
virtual void requestFocus ()
virtual void requestModalFocus ()
virtual void requestModalMouseInputFocus ()
virtual void requestMoveToBottom ()
virtual void requestMoveToTop ()
void resizeToContent ()
void setActionEventId (std::string const &actionEventId)
virtual void setBackgroundColor (Color const &color)
virtual void setBaseColor (Color const &color)
virtual void setBorderColor (Color const &color)
void setBorderSize (unsigned int size)
void setDimension (Rectangle const &dimension)
void setEnabled (bool enabled)
void setFixedSize (Size const &size)
void setFocusable (bool focusable)
virtual void setFont (Font *font)
virtual void setForegroundColor (Color const &color)
void setHeight (int height)
void setHorizontalExpand (bool expand)
void setId (std::string const &id)
void setInternalFocusHandler (FocusHandler *internalFocusHandler)
void setLastPosition (int x, int y)
void setMargin (int margin)
void setMarginBottom (int margin)
void setMarginLeft (int margin)
void setMarginRight (int margin)
void setMarginTop (int margin)
void setMaxSize (Size const &size)
void setMinSize (Size const &size)
virtual void setOutlineColor (Color const &color)
void setOutlineSize (unsigned int size)
void setPadding (unsigned int padding)
void setPaddingBottom (unsigned int padding)
void setPaddingLeft (unsigned int padding)
void setPaddingRight (unsigned int padding)
void setPaddingTop (unsigned int padding)
void setPosition (int x, int y)
virtual void setSelectionColor (Color const &color)
virtual void setSelectionMode (SelectionMode mode)
void setSize (int width, int height)
void setTabInEnabled (bool enabled)
void setTabOutEnabled (bool enabled)
void setVerticalExpand (bool expand)
void setVisible (bool visible)
void setWidth (int width)
void setX (int x)
void setY (int y)
virtual void showPart (Rectangle rectangle)
virtual void showWidgetPart (Widget *widget, Rectangle area)
Widget ()
Widget (Widget &&)=delete
Widget (Widget const &)=delete
Protected Member Functions
void adjustSizeImpl ()
Protected Member Functions inherited from fcn::Widget
void add (Widget *widget)
void calculateSize ()
void distributeActionEvent ()
void distributeAncestorHiddenEvent (Widget *ancestor)
void distributeAncestorMovedEvent (Widget *ancestor)
void distributeAncestorShownEvent (Widget *ancestor)
void distributeHiddenEvent ()
void distributeMovedEvent ()
void distributeResizedEvent ()
void distributeShownEvent ()
virtual Widget * findWidgetById (std::string const &id)
std::list< Widget * > const & getChildren () const
virtual void remove (Widget *widget)
virtual void removeAllChildren ()
void resizeToChildren ()
Protected Attributes
Image const * mBarImage
Image const * mForegroundImage
bool mInternalImage
int mMaxValue
bool mOpaque
Orientation mOrientation
int mValue
Protected Attributes inherited from fcn::Widget
std::string mActionEventId
std::list< ActionListener * > mActionListeners
Color mBackgroundColor {0xf9fafb}
Color mBaseColor {0xe5e7eb}
Color mBorderColor {0xd1d5db}
unsigned int mBorderSize {0}
std::list< Widget * > mChildren
Font * mCurrentFont {nullptr}
std::list< DeathListener * > mDeathListeners
Rectangle mDimension
bool mEnabled {true}
Size mFixedSize {-1, -1}
bool mFixedSizeUsed {false}
bool mFocusable {false}
FocusHandler * mFocusHandler {nullptr}
std::list< FocusListener * > mFocusListeners
Color mForegroundColor {0x1f2933}
bool mHExpand {false}
std::string mId
FocusHandler * mInternalFocusHandler {nullptr}
std::list< KeyListener * > mKeyListeners
int mLastX {0}
int mLastY {0}
int mMarginBottom {0}
int mMarginLeft {0}
int mMarginRight {0}
int mMarginTop {0}
Size mMaxSize {std::numeric_limits<int>::max(), std::numeric_limits<int>::max()}
Size mMinSize {0, 0}
std::list< MouseListener * > mMouseListeners
Rectangle mOffsetRect
Color mOutlineColor {0x9ca3af}
unsigned int mOutlineSize {0}
unsigned int mPaddingBottom {0}
unsigned int mPaddingLeft {0}
unsigned int mPaddingRight {0}
unsigned int mPaddingTop {0}
Widget * mParent {nullptr}
Color mSelectionColor {0x3b82f6}
SelectionMode mSelectionMode {SelectionMode::None}
bool mTabIn {true}
bool mTabOut {true}
bool mVExpand {false}
bool mVisible {true}
std::list< WidgetListener * > mWidgetListeners
Additional Inherited Members
Static Public Member Functions inherited from fcn::Widget
static DeathListener * _getGuiDeathListener ()
static VisibilityEventHandler * _getVisibilityEventHandler ()
static void _setGuiDeathListener (DeathListener *deathListener)
static void _setVisibilityEventHandler (VisibilityEventHandler *visibilityEventHandler)
static void setGlobalFont (Font *font)
static bool widgetExists (Widget const *widget)
Static Protected Attributes inherited from fcn::Widget
static DefaultFont mDefaultFont
static Font * mGlobalFont = nullptr
static DeathListener * mGuiDeathListener = nullptr
static VisibilityEventHandler * mVisibilityEventHandler = nullptr
static std::list< Widget * > mWidgetInstances
Detailed Description
Displays progress using images.
Definition at line 23 of file imageprogressbar.hpp.
Member Enumeration Documentation
Orientation
enum class fcn::ImageProgressBar::Orientation : uint8_t strong
Orientation of the progress bar (horizontal or vertical).
Definition at line 27 of file imageprogressbar.hpp.
Constructor & Destructor Documentation
ImageProgressBar() [1/3]
fcn::ImageProgressBar::ImageProgressBar ()
Definition at line 16 of file imageprogressbar.cpp.
ImageProgressBar() [2/3]
fcn::ImageProgressBar::ImageProgressBar (Image * image, int maxValue)
Constructor.
The image passed is not owned by this object.
Parameters
image Image used by the progress bar.
maxValue Value when the progress bar is full.
Definition at line 27 of file imageprogressbar.cpp.
References adjustSizeImpl(), mBarImage, mForegroundImage, mInternalImage, mMaxValue, mOpaque, mOrientation, and mValue.
ImageProgressBar() [3/3]
fcn::ImageProgressBar::ImageProgressBar (std::string const & filename, int maxValue)
Constructor.
The image indicated by filename is opened and it's owned by this object.
Parameters
filename Filename of the image to be used by the progress bar.
maxValue Value when the progress bar is full.
Definition at line 39 of file imageprogressbar.cpp.
References adjustSizeImpl(), mBarImage, mForegroundImage, mInternalImage, mMaxValue, mOpaque, mOrientation, and mValue.
~ImageProgressBar()
fcn::ImageProgressBar::~ImageProgressBar () override
Definition at line 52 of file imageprogressbar.cpp.
Member Function Documentation
adjustSize()
void fcn::ImageProgressBar::adjustSize () override virtual
Resizes the widget's size to fit the content exactly.
Reimplemented from fcn::Widget.
Definition at line 201 of file imageprogressbar.cpp.
References adjustSizeImpl().
adjustSizeImpl()
void fcn::ImageProgressBar::adjustSizeImpl () protected
Adjusts the size of the progress bar to fit the content.
The public adjustSize() method serves as a virtual entry point for polymorphism, while this adjustSizeImpl() method contains the concrete implementation of the resizing logic.
See also
adjustSize (virtual entry point for polymorphism)
Definition at line 206 of file imageprogressbar.cpp.
References fcn::Widget::getBorderSize(), fcn::Widget::getPaddingBottom(), fcn::Widget::getPaddingLeft(), fcn::Widget::getPaddingRight(), fcn::Widget::getPaddingTop(), mBarImage, and fcn::Widget::setSize().
Referenced by adjustSize(), ImageProgressBar(), ImageProgressBar(), resizeToContent(), setBarImage(), and setForegroundImage().
draw()
void fcn::ImageProgressBar::draw (Graphics * graphics) override virtual
Draws this ImageProgressBar.
Implements fcn::Widget.
Definition at line 59 of file imageprogressbar.cpp.
References fcn::Widget::drawBorder(), fcn::Graphics::drawImage(), fcn::Widget::drawSelectionFrame(), fcn::Graphics::fillRectangle(), fcn::Widget::getBackgroundColor(), fcn::Widget::getBorderSize(), fcn::Widget::getHeight(), getOrientation(), fcn::Widget::getPaddingLeft(), fcn::Widget::getPaddingTop(), fcn::Widget::getSelectionColor(), fcn::Widget::getSelectionMode(), fcn::Widget::getWidth(), fcn::Widget::isFocused(), isOpaque(), mBarImage, mForegroundImage, mMaxValue, mValue, fcn::Graphics::popClipArea(), fcn::Graphics::pushClipArea(), and fcn::Graphics::setColor().
getBarImage()
Image const * fcn::ImageProgressBar::getBarImage () const
Returns
The image used by this Bar.
Definition at line 137 of file imageprogressbar.cpp.
References mBarImage.
getForegroundImage()
Image const * fcn::ImageProgressBar::getForegroundImage () const
Returns
The image used as overlay by this Bar.
Definition at line 148 of file imageprogressbar.cpp.
References mForegroundImage.
getMaxValue()
int fcn::ImageProgressBar::getMaxValue () const
Gets the max value of the bar.
Returns
The max value of the bar.
Definition at line 174 of file imageprogressbar.cpp.
References mMaxValue.
getOrientation()
ImageProgressBar::Orientation fcn::ImageProgressBar::getOrientation () const
Returns
Orientation of this ImageProgressBar.
Definition at line 164 of file imageprogressbar.cpp.
References mOrientation.
Referenced by draw().
getValue()
int fcn::ImageProgressBar::getValue () const
Gets the value of the bar.
Returns
The value of the bar.
Definition at line 190 of file imageprogressbar.cpp.
References mValue.
isOpaque()
bool fcn::ImageProgressBar::isOpaque () const
Returns
Whether this ImageProgressBar is opaque or not.
Definition at line 120 of file imageprogressbar.cpp.
References mOpaque.
Referenced by draw().
resizeToContent() [1/2]
void fcn::Widget::resizeToContent () inline
Resizes the widget's size to fit the content exactly, calls recursively all childs.
This is a convenience wrapper that calls resizeToContent(true).
Definition at line 1417 of file widget.hpp.
resizeToContent() [2/2]
void fcn::ImageProgressBar::resizeToContent (bool recursion) override virtual
Resize this widget to fit its content.
Parameters
recursion If true, perform the resize operation recursively on children.
Reimplemented from fcn::Widget.
Definition at line 195 of file imageprogressbar.cpp.
References adjustSizeImpl().
setBarImage()
void fcn::ImageProgressBar::setBarImage (Image * image)
Sets the Bar image.
The image passed is not owned by this object.
Parameters
image Image used by the progress bar.
Definition at line 125 of file imageprogressbar.cpp.
References adjustSizeImpl(), mBarImage, and mInternalImage.
setForegroundImage()
void fcn::ImageProgressBar::setForegroundImage (Image * image)
Sets the foreground image.
The image passed is not owned by this object.
Parameters
image Image used as overlay by the progress bar.
Definition at line 142 of file imageprogressbar.cpp.
References adjustSizeImpl(), and mForegroundImage.
setMaxValue()
void fcn::ImageProgressBar::setMaxValue (int value)
Sets the max value of the bar.
Parameters
value The max value of the bar.
Definition at line 169 of file imageprogressbar.cpp.
References mMaxValue.
setOpaque()
void fcn::ImageProgressBar::setOpaque (bool opaque)
Sets the opacity of the ImageProgressBar.
Parameters
opaque True if opaque, false otherwise.
Definition at line 115 of file imageprogressbar.cpp.
References mOpaque.
setOrientation()
void fcn::ImageProgressBar::setOrientation (Orientation orientation)
Sets the ImageProgressBar's orientation.
Parameters
orientation Desired orientation.
Definition at line 153 of file imageprogressbar.cpp.
References mOrientation.
setValue()
void fcn::ImageProgressBar::setValue (int value)
Sets the value of the bar.
Parameters
value In the range of 0-max.
Definition at line 179 of file imageprogressbar.cpp.
References mMaxValue, and mValue.
Member Data Documentation
mBarImage
Image const* fcn::ImageProgressBar::mBarImage protected
Bar image.
Definition at line 164 of file imageprogressbar.hpp.
Referenced by adjustSizeImpl(), draw(), getBarImage(), ImageProgressBar(), ImageProgressBar(), and setBarImage().
mForegroundImage
Image const* fcn::ImageProgressBar::mForegroundImage protected
Foreground image.
Definition at line 169 of file imageprogressbar.hpp.
Referenced by draw(), getForegroundImage(), ImageProgressBar(), ImageProgressBar(), and setForegroundImage().
mInternalImage
bool fcn::ImageProgressBar::mInternalImage protected
True if the image has been loaded internally, false otherwise.
An image not loaded internally should not be deleted in the destructor.
Definition at line 176 of file imageprogressbar.hpp.
Referenced by ImageProgressBar(), ImageProgressBar(), and setBarImage().
mMaxValue
int fcn::ImageProgressBar::mMaxValue protected
Value when progress bar is full.
Definition at line 181 of file imageprogressbar.hpp.
Referenced by draw(), getMaxValue(), ImageProgressBar(), ImageProgressBar(), setMaxValue(), and setValue().
mOpaque
bool fcn::ImageProgressBar::mOpaque protected
True if the widget is opaque, false otherwise.
Definition at line 196 of file imageprogressbar.hpp.
Referenced by ImageProgressBar(), ImageProgressBar(), isOpaque(), and setOpaque().
mOrientation
Orientation fcn::ImageProgressBar::mOrientation protected
ImageProgressBar's orientation.
Definition at line 191 of file imageprogressbar.hpp.
Referenced by getOrientation(), ImageProgressBar(), ImageProgressBar(), and setOrientation().
mValue
int fcn::ImageProgressBar::mValue protected
Holds the current progress bar value.
Definition at line 186 of file imageprogressbar.hpp.
Referenced by draw(), getValue(), ImageProgressBar(), ImageProgressBar(), and setValue().
The documentation for this class was generated from the following files:
imageprogressbar.hpp
imageprogressbar.cpp