FifeGUI: fcn::Size Class Reference
fcn::Size Class Reference
Utilities & Math
#include <size.hpp>
Public Member Functions
int getHeight () const
int getWidth () const
Size & operator= (Size &&)=default
Size & operator= (Size const &)=default
void setHeight (int height)
void setWidth (int width)
Size (int width=0, int height=0)
Size (Size &&)=default
Size (Size const &)=default
Detailed Description
Represents dimensions defined by width and height.
Definition at line 17 of file size.hpp.
Constructor & Destructor Documentation
Size()
fcn::Size::Size (int width = 0, int height = 0) explicit
Constructor initializes size values.
Parameters
width Width of size.
height Height of size.
Definition at line 9 of file size.cpp.
Member Function Documentation
getHeight()
int fcn::Size::getHeight () const
Returns
Height of size.
Definition at line 16 of file size.cpp.
Referenced by fcn::ScrollArea::adjustSize(), and fcn::ScrollArea::resizeToContent().
getWidth()
int fcn::Size::getWidth () const
Returns
Width of size.
Definition at line 11 of file size.cpp.
Referenced by fcn::ScrollArea::adjustSize(), and fcn::ScrollArea::resizeToContent().
setHeight()
void fcn::Size::setHeight (int height)
Sets the height of size.
Parameters
height Desired height.
Definition at line 26 of file size.cpp.
setWidth()
void fcn::Size::setWidth (int width)
Sets the width of size.
Parameters
width Desired width.
Definition at line 21 of file size.cpp.
The documentation for this class was generated from the following files:
size.hpp
size.cpp